import {z} from 'zod';
import {canonicalSha256} from './canonical.js';
import {authorityTupleSchema,associationV3Schema,sourceReadbackV3Schema,composeHash,wireSchema,hash,runtimeSchema} from './composedSmsContract.js';
export const CORRECTION_V2='native-compose-sms-correction/v2' as const;
export const CORRECTION_DISPATCH='native-compose-sms-correction-dispatch/v1' as const;
const uuid=z.string().uuid().regex(/^[0-9a-f-]+$/),time=z.string().regex(/^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d\.\d{3}Z$/).datetime(),positive=z.number().int().positive().safe();
export const lineageSchema=z.object({schemaVersion:z.literal('native-compose-sms-action-lineage/v1'),nativeIssuer:z.string().url().refine(s=>new URL(s).protocol==='https:'&&new URL(s).origin===s),businessId:uuid,decisionId:uuid,channel:z.literal('sms'),originalActionDigest:hash,nativeActionId:uuid}).strict();
export const originalActionDigest=(businessId:string,decisionId:string)=>canonicalSha256({business_id:businessId,decision_id:decisionId,channel:'sms'});
export function verifyLineage(raw:unknown){const l=lineageSchema.parse(raw);if(l.originalActionDigest!==originalActionDigest(l.businessId,l.decisionId))throw Error('Invalid original action digest');return l;}
export const lineageHash=(l:z.infer<typeof lineageSchema>)=>composeHash('native-compose-sms/action-lineage/v1',verifyLineage(l));
export const correctionDispatchSchema=authorityTupleSchema.omit({sourceInstructionId:true,sourceInstructionHash:true}).extend({
 nativeActionId:uuid,authorityId:uuid,businessId:uuid,ownerConversationId:uuid,executorConversationId:uuid,canonicalCaseId:uuid,contactCaseId:uuid,senderReceiptId:uuid,
 sourceOrigin:z.string().url().refine(s=>new URL(s).protocol==='https:'&&new URL(s).origin===s),
 executorPrincipalId:z.string().regex(/^veneer:[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/),runtime:z.object({projectId:uuid,environmentId:uuid,serviceId:uuid}).strict(),
 proofKind:z.literal(CORRECTION_V2),correctionAuthorityHash:hash,correctionSourceKind:z.enum(['direct_message','result_reply']),correctionSourceId:uuid,correctionSourceHash:hash,contextHash:hash,decisionId:uuid,decisionVersion:positive,decisionProposalHash:hash,decisionHandlingRevision:z.number().int().nonnegative().safe(),nativeBindingHash:hash,reviewHash:hash,originalActionDigest:hash,lineageHash:hash,derivedAt:time,authorityExpiresAt:time,
}).strict();
export type CorrectionDispatchAuthority=z.infer<typeof correctionDispatchSchema>;
export const correctionScopeHash=(a:CorrectionDispatchAuthority)=>composeHash('native-compose-sms/correction-scope/v1',Object.fromEntries(['businessId','ownerConversationId','executorConversationId','executorPrincipalId','canonicalCaseId','canonicalTicket','contactCaseId','contactTicket','payloadHash','wirePayloadHash'].map(k=>[k,a[k as keyof CorrectionDispatchAuthority]])));
export function verifyCorrectionDispatch(raw:unknown){const a=correctionDispatchSchema.parse(raw),{authorityHash,...tuple}=a;
 const wire=wireSchema.parse(Object.fromEntries(Object.keys(wireSchema.shape).map(k=>[k,a[k as keyof CorrectionDispatchAuthority]])));
 if(composeHash('native-compose-sms/correction-dispatch-authority/v1',tuple)!==authorityHash||composeHash('native-compose-sms/wire/v1',wire)!==a.wirePayloadHash||correctionScopeHash(a)!==a.scopeHash||a.originalActionDigest!==originalActionDigest(a.businessId,a.decisionId)||a.idempotencyKey!==`veneer-compose-sms:${a.nativeActionId}`||Date.parse(a.authorityExpiresAt)<=Date.parse(a.derivedAt))throw Error('Invalid correction authority commitments');return a;
}
export const correctionBindingHash=(r:{registrationId:string;revision:number;sourceRegistrationHash:string},a:CorrectionDispatchAuthority)=>composeHash('native-compose-sms/correction-dispatch-binding/v1',{registrationId:r.registrationId,registrationRevision:r.revision,sourceRegistrationHash:r.sourceRegistrationHash,...Object.fromEntries(['nativeActionId','authorityId','authorityRevision','authorityHash','proofKind','originalActionDigest','lineageHash','scopeHash','materialHash','senderReceiptId','senderReceiptRevision','wirePayloadHash','executorConversationId','executorPrincipalId','canonicalCaseId','canonicalTicket','contactCaseId','contactTicket','idempotencyKey'].map(k=>[k,a[k as keyof CorrectionDispatchAuthority]]))});
export const correctionAssociationSchema=associationV3Schema.extend({schemaVersion:z.literal(CORRECTION_DISPATCH),nativeActionId:uuid,authorityId:uuid,nativeClaimId:uuid,sourcePrepareId:uuid,requestKey:uuid}).strict();
export const correctionReadbackSchema=sourceReadbackV3Schema.innerType().extend({schemaVersion:z.literal(CORRECTION_DISPATCH)}).strict().refine(p=>p.state!=='REDEEMING'||p.redeemRequestKey!==null,'REDEEMING requires durable UUID');
export const lineageEnvelopeSchema=z.object({schemaVersion:z.literal('native-compose-sms-action-lineage/v1'),registrationId:uuid,registrationRevision:positive,sourceRegistrationHash:hash,lineage:lineageSchema,observedAt:time,expiresAt:time,execute:z.literal(false)}).strict();
export const correctionEnvelopeSchema=lineageEnvelopeSchema.extend({schemaVersion:z.literal(CORRECTION_DISPATCH),authority:correctionDispatchSchema}).strict().superRefine((v,c)=>{try{const a=verifyCorrectionDispatch(v.authority),l=verifyLineage(v.lineage);if(a.lineageHash!==lineageHash(l)||a.originalActionDigest!==l.originalActionDigest||a.nativeActionId!==l.nativeActionId||a.businessId!==l.businessId||a.decisionId!==l.decisionId||Date.parse(v.expiresAt)<=Date.parse(v.observedAt)||Date.parse(v.expiresAt)>Math.min(Date.parse(v.observedAt)+15000,Date.parse(a.authorityExpiresAt)))throw Error();}catch{c.addIssue({code:'custom',message:'Correction envelope binding mismatch'});}});
export const correctionPrepareSchema=z.object({schemaVersion:z.literal(CORRECTION_DISPATCH),nativeActionId:uuid,authorityId:uuid,authorityRevision:z.literal(1)}).strict();
export const correctionDispatchInputSchema=z.object({schemaVersion:z.literal(CORRECTION_DISPATCH),nativeClaimId:uuid}).strict();
export const correctionPrepareResultSchema=z.object({schemaVersion:z.literal(CORRECTION_DISPATCH),prepareId:uuid,nativeActionId:uuid,bindingHash:hash,state:z.literal('PREPARED'),observedAt:time,prepareExpiresAt:time,execute:z.literal(false)}).strict();
export const correctionAssociationResultSchema=z.object({schemaVersion:z.literal(CORRECTION_DISPATCH),associationId:uuid,nativeActionId:uuid,nativeClaimId:uuid,sourcePrepareId:uuid,bindingHash:hash,state:z.enum(['ASSOCIATED','REVOKED']),dispatchEntitlement:z.boolean(),execute:z.literal(false),issuedAt:time,expiresAt:time}).strict();
