import {z} from 'zod';
import {canonicalSha256} from './canonical.js';
export const composeHash=(domain:string,value:unknown)=>canonicalSha256({domain,value});
export const uuid=z.string().uuid(), hash=z.string().regex(/^[a-f0-9]{64}$/), text=z.string().min(1).max(200), time=z.string().datetime();
export const runtimeSchema=z.object({projectId:uuid,environmentId:uuid,serviceId:uuid}).strict();
const phone=z.string().regex(/^\+[1-9][0-9]{7,14}$/);
export const wireSchema=z.object({senderAccountId:z.string().regex(/^AC[0-9a-fA-F]{32}$/),fromPhone:phone,toPhone:phone,wireBody:z.string().min(1).max(1600).refine(s=>Buffer.from(s,'utf8').toString('utf8')===s,'Exact valid UTF-8 text required'),media:z.array(z.never()).length(0),normalizationPolicy:z.literal('sms-identity-utf8/v1')}).strict();
export const authorityTupleSchema=wireSchema.extend({nativeActionId:uuid,authorityId:uuid,authorityRevision:z.literal(1),authorityHash:hash,payloadHash:hash,sourceInstructionHash:hash,scopeHash:hash,materialHash:hash,materialHashVersion:z.literal('compose-correspondence-material/v1'),sourceInstructionId:uuid,businessId:uuid,sourceOrigin:z.literal('https://orderops-dev-web-production.up.railway.app'),runtime:runtimeSchema,ownerConversationId:uuid,executorConversationId:uuid,executorPrincipalId:text,canonicalCaseId:uuid,canonicalTicket:text,contactCaseId:uuid,contactTicket:text,senderReceiptId:uuid,senderReceiptRevision:z.number().int().positive().safe(),wirePayloadHash:hash,idempotencyKey:text}).strict();
export type ComposeAuthority=z.infer<typeof authorityTupleSchema>;
export const associationInputSchema=z.object({schemaVersion:z.literal('native-compose-sms/v1'),nativeActionId:uuid,authorityId:uuid,authorityRevision:z.literal(1),nativeClaimId:uuid,sourcePrepareId:uuid,bindingHash:hash,requestKey:uuid}).strict();
export const sourceReadbackSchema=z.object({schemaVersion:z.literal('native-compose-sms/v1'),nativeActionId:uuid,prepareId:uuid,bindingHash:hash,nativeClaimId:uuid.nullable(),associationId:uuid.nullable(),attemptId:uuid.nullable(),state:z.enum(['PREPARED','REDEEMING','SENDING','UNKNOWN','REJECTED','SENT_ACCEPTED','REVOKED','EXPIRED']),authorityHash:hash,wirePayloadHash:hash,idempotencyKey:text,providerReceipt:z.object({provider:z.literal('twilio'),providerAccountId:text,providerMessageId:text,fromPhone:phone,toPhone:phone,wirePayloadHash:hash,acceptanceStatus:z.enum(['accepted','queued','sending','sent','delivered']),deliveryStatus:z.string().max(100).nullable(),evidenceOrigin:text,checkedAt:time}).strict().nullable(),observedAt:time,prepareExpiresAt:time,redeemRequestKey:uuid.nullable(),execute:z.literal(false)}).strict().refine(p=>p.state!=='REDEEMING'||p.redeemRequestKey!==null,{message:'REDEEMING requires a durable UUID redemption key',path:['redeemRequestKey']});
export function bindingHash(reg:{registrationId:string;revision:number;sourceRegistrationHash:string},a:ComposeAuthority){return composeHash('native-compose-sms/binding/v1',{registrationId:reg.registrationId,registrationRevision:reg.revision,sourceRegistrationHash:reg.sourceRegistrationHash,...Object.fromEntries(['nativeActionId','authorityId','authorityRevision','authorityHash','scopeHash','materialHash','senderReceiptId','senderReceiptRevision','wirePayloadHash','executorConversationId','executorPrincipalId','canonicalCaseId','canonicalTicket','contactCaseId','contactTicket','idempotencyKey'].map(k=>[k,a[k as keyof ComposeAuthority]]))});}
export function verifyAuthority(value:unknown){const a=authorityTupleSchema.parse(value),{authorityHash,...tuple}=a;
 if(composeHash('native-compose-sms/authority/v1',tuple)!==authorityHash||composeHash('native-compose-sms/wire/v1',wireSchema.parse(Object.fromEntries(Object.keys(wireSchema.shape).map(k=>[k,a[k as keyof ComposeAuthority]]))))!==a.wirePayloadHash||a.idempotencyKey!==`veneer-compose-sms:${a.nativeActionId}`)throw Error('Invalid immutable authority hashes');return a;}
// Called only AFTER authenticating the complete source envelope, including identity.
// A new namespace deliberately does not alter BUILD432's persisted material digest.
export function composeMaterialHash(stable:Record<string,unknown>&{identity:Record<string,unknown>}){const {principalId,...identity}=stable.identity;return composeHash('compose-correspondence-material/v1',{...stable,identity});}
