import { z } from 'zod';
import { canonicalSha256 } from './canonical.js';
export const uuid = z.string().uuid(), hash = z.string().regex(/^[a-f0-9]{64}$/), text = z.string().min(1).max(500);
export const decimalId=z.string().regex(/^[1-9][0-9]{0,39}$/);
export const revision = z.number().int().positive().safe(), time = z.string().datetime({offset:true});
export const H = (domain:string,value:unknown) => canonicalSha256({domain,value});
export const runtimeSchema=z.object({projectId:uuid,environmentId:uuid,serviceId:uuid}).strict();
export const policySchema=z.object({kind:z.literal('original_payment_refund_only'),returnPrerequisite:z.literal(false),restock:z.literal(false),notification:z.literal(false),customerSend:z.literal(false),label:z.literal(false),insurance:z.literal(false)}).strict();
export const targetSchema=z.object({canonicalCaseId:uuid,orderId:uuid,shopifyOrderId:decimalId,orderNumber:text,customerId:text,paymentId:decimalId,currency:z.literal('USD'),amountMinor:revision,items:z.array(z.object({id:uuid,shopifyLineItemId:decimalId,quantity:revision,amountMinor:revision}).strict()).min(1).max(100),taxMinor:z.number().int().nonnegative().safe(),shippingMinor:z.number().int().nonnegative().safe(),policy:policySchema}).strict();
export const pinsSchema=z.object({decisionId:uuid,version:revision,proposalHash:hash,approvalEventId:uuid,answerHash:hash,instructionId:uuid,instructionHash:hash,recordingEventId:uuid,authorUserId:revision,instructionVersion:revision,instructionHandlingRevision:z.number().int().nonnegative().safe()}).strict();
const acceptance=z.object({receiptHash:hash,implementationHash:hash,writerManifestHash:hash,contractHash:hash,reviewedBy:uuid,reviewedAt:time,expiresAt:time}).strict();
export const registrationSchema=z.object({schemaVersion:z.literal('exact-refund-registration/v1'),id:uuid,revision,active:z.boolean(),businessId:uuid,ownerUserId:revision,executorConversationId:uuid,executorPrincipalId:text,servicePrincipalId:text,sourceOrigin:z.string().url().refine(v=>{const u=new URL(v);return u.protocol==='https:'&&u.origin===v&&!u.username&&!u.password;}),runtime:runtimeSchema,storeId:decimalId,accountId:text,audience:text,cfClientId:text,bearerHash:hash,readerCredential:z.object({project:text,config:text,name:z.string().regex(/^EXACT_REFUND_[A-Z0-9_]+$/)}).strict(),enrollment:z.object({id:uuid,revision,identityEvidenceHash:hash,receiptHash:hash}).strict(),custodyReceiptHash:hash,reviewReceiptHash:hash,pins:pinsSchema,target:targetSchema,acceptance,expiresAt:time,credentialExpiresAt:time,readerExpiresAt:time,custodyExpiresAt:time}).strict();
export const registrySchema=z.object({schemaVersion:z.literal('exact-refund-registry/v1'),registrations:z.array(registrationSchema).max(50)}).strict();
export type Registration=z.infer<typeof registrationSchema>;
export const revisionsSchema=z.object({case:text,order:text,customer:text,payment:text,items:hash,material:hash,refundInventory:hash}).strict();
export const identitySchema=z.object({registrationId:uuid,registrationRevision:revision,registrationHash:hash,businessId:uuid,executorConversationId:uuid,executorPrincipalId:text,servicePrincipalId:text,sourceOrigin:z.string().url(),runtime:runtimeSchema,storeId:decimalId,accountId:text,enrollmentId:uuid,enrollmentRevision:revision,identityEvidenceHash:hash}).strict();
export const evidenceSchema=z.object({schemaVersion:z.literal('exact-refund-evidence/v1'),identity:identitySchema,target:targetSchema,revisions:revisionsSchema,sourceCaptureAt:time,expiresAt:time,snapshotHash:hash,payment:z.object({kind:z.literal('successful_original_payment'),amountMinor:revision,remainingMinor:z.number().int().nonnegative().safe(),currency:z.literal('USD')}).strict(),coverage:z.object({writerManifestHash:hash,implementationHash:hash,complete:z.boolean(),omissions:z.array(text).max(50),priorEffects:z.array(z.object({id:text,state:z.enum(['SUCCESS','UNKNOWN','RESERVED','FAILED','ROLLED_BACK'])}).strict()).max(500)}).strict(),blockers:z.array(text).max(100)}).strict();
export const evidenceMaterial=(e:z.infer<typeof evidenceSchema>)=>{const {sourceCaptureAt,expiresAt,snapshotHash,...v}=e;return v;};
export const inspectionInput=z.object({registrationId:uuid}).strict();
export const reviewSchema=z.object({interpretation:z.literal('exact_approved_refund_only'),explanation:z.string().min(20).max(4000),citations:z.array(z.object({kind:z.enum(['discussion','direct','reply']),id:uuid,text:z.string().min(1).max(20000),classification:z.enum(['supports','resolved_condition','separate_scope','status_only'])}).strict()).max(500),unresolved:z.array(text).length(0)}).strict();
export const issueInput=z.object({registrationId:uuid,inspectionHash:hash,requestKey:uuid,expiresAt:time,review:reviewSchema}).strict();
export const authoritySchema=z.object({schemaVersion:z.literal('exact-refund-authority/v1'),authorityId:uuid,revision:z.literal(1),registrationId:uuid,registrationRevision:revision,registrationHash:hash,runtimeAcceptanceHash:hash,pins:pinsSchema,contextRevision:hash,reviewHash:hash,identity:identitySchema,target:targetSchema,revisions:revisionsSchema,sourceEvidenceHash:hash,sourceCaptureAt:time,originalActionDigest:hash,issuedAt:time,expiresAt:time,authorityHash:hash}).strict();
export type Authority=z.infer<typeof authoritySchema>;
export const authorityHash=(a:Authority)=>{const {authorityHash,...v}=a;return H('exact-refund/authority/v1',v);};
// Conservative order-wide financial fence: cannot evade via a different payment,
// amount, item allocation, case alias, version, executor, request key or registration.
export const actionDigest=(r:Pick<Registration,'businessId'|'storeId'|'target'>)=>H('exact-refund/action/v1',{businessId:r.businessId,storeId:r.storeId,shopifyOrderId:r.target.shopifyOrderId,effect:'refund'});
export const intentBindingSchema=z.object({schemaVersion:z.literal('exact-refund-intent-binding/v1'),identity:identitySchema,authorityId:uuid,authorityHash:hash,originalActionDigest:hash,target:targetSchema,revisions:revisionsSchema,sourceEvidenceHash:hash,sourceIntentId:uuid,requestKey:uuid,providerIdempotencyKey:text,preparedEventId:uuid,preparedAt:time,expiresAt:time}).strict();
export const intentSchema=z.object({schemaVersion:z.literal('exact-refund-intent/v1'),binding:intentBindingSchema,intentHash:hash,state:z.enum(['REDEEMING','SENDING','UNKNOWN','SUCCESS','ROLLED_BACK_TERMINAL','FAILED_TERMINAL']),redeemingEventId:uuid,redeemingAt:time,sendingEventId:uuid.nullable(),sendingAt:time.nullable(),observedAt:time,expiresAt:time,currentEvidence:evidenceSchema,currentReservation:z.object({sourceIntentId:uuid,intentHash:hash,preparedEventId:uuid,exclusion:z.literal('own_reservation_only_not_effects')}).strict(),associationId:uuid.nullable(),attemptId:uuid.nullable(),outcome:z.object({receiptId:text,associationId:uuid.nullable(),attemptId:uuid.nullable(),requestKey:uuid,refundTransactionId:decimalId.nullable(),providerStatus:z.enum(['SUCCESS','UNKNOWN','ROLLED_BACK_TERMINAL','FAILED_TERMINAL']),providerReceiptHash:hash.nullable(),auditEventId:uuid,noRetry:z.literal(true),paymentId:decimalId,refundId:decimalId.nullable(),amountMinor:revision,currency:z.literal('USD'),providerIdempotencyKey:text,state:z.enum(['SUCCESS','UNKNOWN','ROLLED_BACK_TERMINAL','FAILED_TERMINAL']),recordedAt:time}).strict().nullable()}).strict();
export const associationInput=z.object({schemaVersion:z.literal('exact-refund-association/v1'),authorityId:uuid,authorityHash:hash,sourceIntentId:uuid,requestKey:uuid,intentHash:hash}).strict();
export const associationSchema=z.object({schemaVersion:z.literal('exact-refund-association-receipt/v1'),associationId:uuid,authorityId:uuid,authorityHash:hash,registrationId:uuid,originalActionDigest:hash,sourceIntentId:uuid,requestKey:uuid,intentHash:hash,reservedAt:time,dispatchExpiresAt:time}).strict();
export const associationResponse=z.object({execute:z.literal(false),refundEntitlement:z.boolean(),retryAllowed:z.literal(false),association:associationSchema}).strict();
const lookupBase=z.object({execute:z.literal(false),refundEntitlement:z.literal(false),retryAllowed:z.literal(false)});
export const lookupResponse=z.discriminatedUnion('status',[lookupBase.extend({status:z.literal('FOUND'),association:associationSchema}).strict(),lookupBase.extend({status:z.literal('ABSENT'),association:z.null()}).strict()]);
export const reconcileResponse=associationResponse.extend({refundEntitlement:z.literal(false)}).strict();
export const revokeInput=z.object({reason:text}).strict();
export const revokeResponse=z.object({execute:z.literal(false),refundEntitlement:z.literal(false),retryAllowed:z.literal(false),reservationIrrevocable:z.boolean()}).strict();
export const receiptInput=z.object({}).strict();
export const receiptResponse=z.object({execute:z.literal(false),refundEntitlement:z.literal(false),retryAllowed:z.literal(false),associationId:uuid,state:z.enum(['SUCCESS','UNKNOWN','ROLLED_BACK_TERMINAL','FAILED_TERMINAL']),receiptHash:hash,noRetry:z.literal(true)}).strict();
export const exportResponse=z.object({execute:z.literal(false),refundEntitlement:z.literal(false),retryAllowed:z.literal(false),authority:authoritySchema,observedAt:time,expiresAt:time}).strict();
// SHA256 of frozen normative.json, which commits exact schema bytes (this line masked),
// domains, field semantics, routes and failure/linearization policy. Updated only with review.
export const CONTRACT_HASH='42afab55b95731f9ac32229fb08a8cbd2482dba07f3437b2a5330c093f99912b';
export function validateAllocation(t:z.infer<typeof targetSchema>){
 const total=t.items.reduce((n,x)=>n+x.amountMinor,0)+t.taxMinor+t.shippingMinor;
 if(!Number.isSafeInteger(total)||total!==t.amountMinor||new Set(t.items.map(x=>x.id)).size!==t.items.length||new Set(t.items.map(x=>x.shopifyLineItemId)).size!==t.items.length)throw Error('EXACT_ALLOCATION_REQUIRED');
}
export function expectedIdentity(r:Registration){return {registrationId:r.id,registrationRevision:r.revision,registrationHash:canonicalSha256(r),businessId:r.businessId,executorConversationId:r.executorConversationId,executorPrincipalId:r.executorPrincipalId,servicePrincipalId:r.servicePrincipalId,sourceOrigin:r.sourceOrigin,runtime:r.runtime,storeId:r.storeId,accountId:r.accountId,enrollmentId:r.enrollment.id,enrollmentRevision:r.enrollment.revision,identityEvidenceHash:r.enrollment.identityEvidenceHash};}
const same=(a:unknown,b:unknown)=>canonicalSha256(a)===canonicalSha256(b);
export function validateEvidenceBinding(r:Registration,e:z.infer<typeof evidenceSchema>,initial:boolean){
 validateAllocation(e.target);
 if(!same(e.identity,expectedIdentity(r))||!same(e.target,r.target)||e.snapshotHash!==H('exact-refund/evidence/v1',evidenceMaterial(e)))throw Error('SOURCE_BINDING_MISMATCH');
 if(initial&&(!e.coverage.complete||e.coverage.omissions.length||e.blockers.length||e.coverage.priorEffects.length||e.coverage.writerManifestHash!==r.acceptance.writerManifestHash||e.coverage.implementationHash!==r.acceptance.implementationHash||e.payment.remainingMinor<e.target.amountMinor||e.payment.amountMinor<e.target.amountMinor))throw Error('REFUND_COVERAGE_BALANCE_OR_GUARD_BLOCKED');
}
export function validateIntentBinding(r:Registration,a:Authority,i:z.infer<typeof intentSchema>,first:boolean){
 const b=i.binding;
 validateAllocation(a.target);
 if(!same(a.target,r.target)||!same(a.pins,r.pins)||a.registrationId!==r.id||a.registrationRevision!==r.revision||a.registrationHash!==canonicalSha256(r)||a.runtimeAcceptanceHash!==H('exact-refund/acceptance/v1',r.acceptance)||Date.parse(a.expiresAt)>Math.min(...[r.expiresAt,r.credentialExpiresAt,r.readerExpiresAt,r.custodyExpiresAt,r.acceptance.expiresAt].map(Date.parse))||Date.parse(a.expiresAt)<=Date.parse(a.issuedAt))throw Error('AUTHORITY_REGISTRATION_MISMATCH');
 if(i.currentReservation.sourceIntentId!==b.sourceIntentId||i.currentReservation.intentHash!==i.intentHash||i.currentReservation.preparedEventId!==b.preparedEventId)throw Error('CURRENT_RESERVATION_MISMATCH');
 if(a.authorityHash!==authorityHash(a)||a.originalActionDigest!==actionDigest(r)||!same(a.identity,expectedIdentity(r))||!same(b.identity,a.identity)||b.authorityId!==a.authorityId||b.authorityHash!==a.authorityHash||b.originalActionDigest!==a.originalActionDigest||!same(b.target,a.target)||!same(b.revisions,a.revisions)||b.sourceEvidenceHash!==a.sourceEvidenceHash||i.intentHash!==H('exact-refund/intent/v1',b)||Date.parse(b.expiresAt)>Date.parse(a.expiresAt)||Date.parse(b.preparedAt)<Date.parse(a.issuedAt)||Date.parse(b.preparedAt)>Date.parse(i.redeemingAt)||Date.parse(i.redeemingAt)>Date.parse(i.observedAt)||b.preparedEventId===i.redeemingEventId)throw Error('AUTHORITY_INTENT_SCOPE_MISMATCH');
 validateEvidenceBinding(r,i.currentEvidence,first);
 if(first&&i.currentEvidence.snapshotHash!==a.sourceEvidenceHash)throw Error('MATERIAL_CHANGED');
 if((i.sendingEventId===null)!==(i.sendingAt===null))throw Error('SENDING_FENCE_REQUIRED');
 if(i.sendingEventId&&(i.sendingEventId===b.preparedEventId||i.sendingEventId===i.redeemingEventId||!i.associationId||!i.attemptId||Date.parse(i.sendingAt!)<Date.parse(i.redeemingAt)||Date.parse(i.sendingAt!)>Date.parse(i.observedAt)||Date.parse(i.sendingAt!)>=Date.parse(b.expiresAt)))throw Error('SENDING_FENCE_MISMATCH');
 if(i.state==='REDEEMING'&&(i.associationId!==null||i.attemptId!==null||i.outcome!==null||i.sendingEventId!==null))throw Error('REDEEMING_STATE_MISMATCH');
 if(i.state==='SENDING'&&(!i.sendingEventId||i.outcome!==null))throw Error('SENDING_STATE_MISMATCH');
 const o=i.outcome;
 if(o&&(o.associationId!==i.associationId||o.attemptId!==i.attemptId||o.requestKey!==b.requestKey||o.paymentId!==b.target.paymentId||o.amountMinor!==b.target.amountMinor||o.currency!==b.target.currency||o.providerIdempotencyKey!==b.providerIdempotencyKey||o.state!==i.state||o.providerStatus!==i.state||Date.parse(o.recordedAt)>Date.parse(i.observedAt)||Date.parse(o.recordedAt)<Date.parse(i.sendingAt??i.redeemingAt)||[b.preparedEventId,i.redeemingEventId,i.sendingEventId].includes(o.auditEventId)))throw Error('PROVIDER_CORRELATION_MISMATCH');
 if(i.state==='SUCCESS'&&(!i.sendingEventId||!o||!o.refundId||!o.refundTransactionId||!o.providerReceiptHash||o.refundTransactionId===o.paymentId||Date.parse(o.recordedAt)<Date.parse(i.sendingAt!)))throw Error('EXACT_SUCCESS_RECEIPT_REQUIRED');
 if(['ROLLED_BACK_TERMINAL','FAILED_TERMINAL'].includes(i.state)&&!o)throw Error('TERMINAL_AUDIT_REQUIRED');
 if(i.state!=='SUCCESS'&&i.state!=='UNKNOWN'&&o&&(o.refundId!==null||o.refundTransactionId!==null||o.providerReceiptHash!==null))throw Error('NON_SUCCESS_RECEIPT_CONFLICT');
}
