import crypto from 'node:crypto';
import type Database from 'better-sqlite3';
import type {UserRow, ConversationRow} from '../db/db.js';
import {canSendToConversation} from '../conversations/access.js';
import {BotError,createBotService,type Actor} from './service.js';
import {canonicalSha256} from './canonical.js';
import {H,CONTRACT_HASH,registrationSchema,evidenceSchema,evidenceMaterial,authoritySchema,authorityHash,actionDigest,inspectionInput,issueInput,associationInput,intentSchema,validateAllocation,expectedIdentity,validateEvidenceBinding,validateIntentBinding,type Registration,type Authority} from './exactRefundContract.js';
export interface RefundIO {now:()=>number;registration:(id:string)=>unknown;evidence:(r:Registration)=>Promise<unknown>;intent:(r:Registration,id:string)=>Promise<unknown>}
function deny(code:string):never{throw new BotError(409,code);}
const unavailable=():never=>{throw new BotError(503,'REFUND_BOUNDARY_UNAVAILABLE: dedicated accepted integration and enrollment required');};
const eq=(a:unknown,b:unknown)=>canonicalSha256(a)===canonicalSha256(b);
type Stored={id:string;authority_json:string;native_json:string;review_json:string;request_hash:string};
type Assoc={id:string;registration_id:string;authority_id:string;request_hash:string;association_json:string;intent_json:string};
export function exactRefund(db:Database.Database,io:RefundIO){
 const bots=createBotService(db),iso=()=>new Date(io.now()).toISOString();
 function registration(id:string){
  const r=registrationSchema.parse(io.registration(id));
  if(r.id!==id||!r.active||r.acceptance.contractHash!==CONTRACT_HASH||Math.min(...[r.expiresAt,r.credentialExpiresAt,r.readerExpiresAt,r.custodyExpiresAt,r.acceptance.expiresAt].map(Date.parse))<=io.now()||Date.parse(r.acceptance.reviewedAt)>io.now())return unavailable();
  if(!db.prepare("SELECT 1 FROM business_teams b JOIN users u ON u.id=b.owner_id WHERE b.id=? AND b.owner_id=? AND u.status='active'").get(r.businessId,r.ownerUserId))return unavailable();
  const c=db.prepare('SELECT * FROM conversations WHERE id=?').get(r.executorConversationId) as ConversationRow|undefined;
  if(!c||c.archived||c.user_id!==r.ownerUserId||c.business_team_id!==r.businessId||!db.prepare('SELECT 1 FROM bot_registrations WHERE conversation_id=? AND active=1').get(c.id)||!db.prepare('SELECT 1 FROM business_bot_members WHERE conversation_id=? AND team_id=?').get(c.id,r.businessId))return unavailable();
  validateAllocation(r.target);
  return r;
 }
 function owner(a:Actor,r:Registration){if(a.conversationId!==r.executorConversationId||a.user.id!==r.ownerUserId)throw new BotError(403,'ORIGINAL_REFUND_EXECUTOR_REQUIRED');const user=db.prepare("SELECT * FROM users WHERE id=? AND status='active'").get(a.user.id) as UserRow|undefined;const c=db.prepare('SELECT * FROM conversations WHERE id=?').get(r.executorConversationId) as ConversationRow;if(!user||!canSendToConversation(user,c,db))throw new BotError(403,'REFUND_ACCESS_REVOKED');}
 function native(r:Registration){
  const user=db.prepare('SELECT * FROM users WHERE id=?').get(r.ownerUserId) as UserRow;
  const d=bots.read({user,conversationId:r.executorConversationId},r.pins.decisionId);
  if(d.conversation_id!==r.executorConversationId||d.version!==r.pins.version||!['blocked','decided','running','action_pending'].includes(d.state)||d.stale_json)deny('NATIVE_APPROVAL_CHANGED');
  const proposal=JSON.parse(d.proposal_json),answer=JSON.parse(d.answer_json??'null');
  const events=db.prepare('SELECT id,version,kind,actor_id,actor_conversation_id,payload_json,request_key,created_at FROM bot_decision_events WHERE decision_id=? ORDER BY rowid LIMIT 501').all(d.id) as any[];
  const discussion=db.prepare('SELECT t.*,i.version instruction_version,i.handling_revision instruction_handling_revision FROM bot_decision_threads t LEFT JOIN bot_discussion_instructions i ON i.message_id=t.id WHERE t.decision_id=? ORDER BY t.rowid LIMIT 501').all(d.id) as any[];
  const direct=db.prepare('SELECT id,actor_id,text,proposals_json,created_at FROM bot_human_messages WHERE conversation_id=? ORDER BY rowid LIMIT 501').all(d.conversation_id) as any[];
  const replies=db.prepare('SELECT r.id,r.actor_id,r.actor_conversation_id,r.text,r.created_at,t.source_text,t.anchor,t.id thread_id FROM bot_message_replies r JOIN bot_message_threads t ON t.id=r.thread_id WHERE t.conversation_id=? ORDER BY r.rowid LIMIT 501').all(d.conversation_id) as any[];
  const context={proposal,answer,events,discussion,direct,replies,version:d.version,handlingRevision:d.handling_revision,state:d.state,result:d.result_json,parked:d.parked_json};
  if([events,discussion,direct,replies].some(x=>x.length>500)||Buffer.byteLength(JSON.stringify(context))>256000)deny('COMPLETE_NATIVE_CONTEXT_EXCEEDS_BOUND');
  const approval=events.find(x=>x.id===r.pins.approvalEventId),instruction=discussion.find(x=>x.id===r.pins.instructionId),record=events.find(x=>x.id===r.pins.recordingEventId);
  if(!approval||approval.kind!=='answered'||approval.version!==d.version||approval.actor_conversation_id!==null||approval.actor_id!==r.pins.authorUserId||!instruction||instruction.actor_conversation_id!==null||instruction.actor_id!==approval.actor_id||instruction.instruction_version!==d.version||instruction.instruction_version!==r.pins.instructionVersion||instruction.instruction_handling_revision!==r.pins.instructionHandlingRevision)deny('AUTHENTIC_HUMAN_APPROVAL_REQUIRED');
  const raw=JSON.parse(approval.payload_json),recorded=record?JSON.parse(record.payload_json):null;
  if(!answer||answer.action!=='approve'||raw.action!=='approve'||raw.scope!=='this_case'||!eq(answer,{...raw,actor_id:approval.actor_id})||canonicalSha256(raw)!==r.pins.answerHash||canonicalSha256(proposal)!==r.pins.proposalHash||H('exact-refund/instruction/v1',{id:instruction.id,actorId:instruction.actor_id,text:instruction.text,version:instruction.instruction_version})!==r.pins.instructionHash)deny('EXACT_APPROVAL_PIN_MISMATCH');
  if(!record||record.kind!=='discussion_decision'||record.version!==d.version||record.actor_conversation_id!==r.executorConversationId||recorded.message_id!==instruction.id||recorded.author_id!==approval.actor_id||recorded.action!=='approve'||recorded.version!==d.version||recorded.instruction_version!==d.version||approval.request_key!==`discussion-answer:${instruction.id}`)deny('AUTHENTIC_INSTRUCTION_BINDING_REQUIRED');
  const author=db.prepare("SELECT * FROM users WHERE id=? AND status='active'").get(approval.actor_id) as UserRow|undefined,c=db.prepare('SELECT * FROM conversations WHERE id=?').get(d.conversation_id) as ConversationRow;
  if(!author||!canSendToConversation(author,c,db))deny('APPROVER_ACCESS_REVOKED');
  const shared=!!db.prepare('SELECT 1 FROM shared_bot_queues WHERE conversation_id=?').get(c.id);
  if(author.id!==d.assignee_id&&!(shared&&(author.id===c.user_id||db.prepare('SELECT 1 FROM employee_bot_access WHERE user_id=? AND conversation_id=?').get(author.id,c.id))))deny('APPROVER_AUTHORITY_REVOKED');
  const human=[...discussion.filter(x=>x.actor_conversation_id===null).map(x=>({kind:'discussion',id:x.id,text:x.text})),...direct.map(x=>({kind:'direct',id:x.id,text:x.text})),...replies.filter(x=>x.actor_conversation_id===null).map(x=>({kind:'reply',id:x.id,text:x.text}))];
  const contextRevision=H('exact-refund/context/v1',{context,registrationHash:canonicalSha256(r),author:{id:author.id,status:author.status,role:author.role},executor:r.executorConversationId});
  return {context,contextRevision,human};
 }
 const identity=expectedIdentity;
 function fresh(observed:string,expires:string){const at=Date.parse(observed),end=Date.parse(expires);if(at>io.now()||end<=io.now()||end<=at||end-at>15000||io.now()-at>15000)deny('SOURCE_OBSERVATION_EXPIRED');}
 function evidence(r:Registration,raw:unknown,initial=true){
  const e=evidenceSchema.parse(raw);fresh(e.sourceCaptureAt,e.expiresAt);
  validateEvidenceBinding(r,e,initial);
  return e;
 }
 async function inspect(a:Actor,raw:unknown){const p=inspectionInput.parse(raw),r=registration(p.registrationId);owner(a,r);const n=native(r),e=evidence(r,await io.evidence(r));if(!eq(registration(r.id),r)||native(r).contextRevision!==n.contextRevision)deny('CONTEXT_OR_TRUST_DRIFT');const binding={registrationHash:canonicalSha256(r),contextRevision:n.contextRevision,sourceEvidenceHash:e.snapshotHash,target:r.target,revisions:e.revisions};return {execute:false as const,refundEntitlement:false as const,inspectionHash:H('exact-refund/inspection/v1',binding),binding,native:n,evidence:e};}
 function stored(id:string){const row=db.prepare('SELECT * FROM exact_refund_authorities WHERE id=?').get(id) as Stored|undefined;if(!row)throw new BotError(404,'REFUND_AUTHORITY_NOT_FOUND');return {row,a:authoritySchema.parse(JSON.parse(row.authority_json))};}
 function current(id:string,r:Registration){const {row,a}=stored(id);if(a.registrationId!==r.id||a.registrationHash!==canonicalSha256(r)||a.authorityHash!==authorityHash(a)||Date.parse(a.expiresAt)<=io.now()||db.prepare('SELECT 1 FROM exact_refund_revocations WHERE authority_id=?').get(id))deny('REFUND_AUTHORITY_EXPIRED_REVOKED_OR_CHANGED');const n=native(r);if(n.contextRevision!==a.contextRevision)deny('NATIVE_CONTEXT_DRIFT');return {row,a};}
 function summary(row:Assoc,entitlement=false){return {execute:false as const,refundEntitlement:entitlement,retryAllowed:false as const,association:JSON.parse(row.association_json)};}
 function readAssociation(r:Registration,id:string){const row=db.prepare('SELECT * FROM exact_refund_associations WHERE id=? AND registration_id=?').get(id,r.id) as Assoc|undefined;if(!row)throw new BotError(404,'REFUND_ASSOCIATION_NOT_FOUND');return row;}
 async function intent(r:Registration,id:string,first:boolean){const i=intentSchema.parse(await io.intent(r,id));fresh(i.observedAt,i.expiresAt);if(!eq(registration(r.id),r))deny('TRUST_DRIFT');const b=i.binding;if(b.sourceIntentId!==id||!eq(b.identity,identity(r))||i.intentHash!==H('exact-refund/intent/v1',b)||i.redeemingEventId===b.preparedEventId||Date.parse(b.preparedAt)>Date.parse(i.redeemingAt)||Date.parse(i.redeemingAt)>Date.parse(i.observedAt))deny('DURABLE_INTENT_MISMATCH');
  if(first){evidence(r,i.currentEvidence);if(i.state!=='REDEEMING'||i.associationId!==null||i.attemptId!==null||i.outcome!==null||Date.parse(b.expiresAt)<=io.now())deny('FIRST_REDEEMING_INTENT_REQUIRED');}return i;}
 return {registration,identity,inspect,
  async issue(a:Actor,raw:unknown){const p=issueInput.parse(raw),r=registration(p.registrationId);owner(a,r);const requestHash=H('exact-refund/issue-request/v1',p);const old=db.prepare('SELECT * FROM exact_refund_authorities WHERE registration_id=? AND request_key=?').get(r.id,p.requestKey) as Stored|undefined;if(old){if(old.request_hash!==requestHash)deny('REQUEST_CONFLICT');return {execute:false,refundEntitlement:false,authority:JSON.parse(old.authority_json),replayed:true};}
   const x=await inspect(a,{registrationId:r.id});if(x.inspectionHash!==p.inspectionHash)deny('INSPECTION_CHANGED');const seen=new Set<string>();for(const c of p.review.citations){const key=c.kind+':'+c.id;if(seen.has(key)||!x.native.human.some(h=>h.kind===c.kind&&h.id===c.id&&h.text===c.text))deny('EXACT_COMPLETE_REVIEW_REQUIRED');seen.add(key);}if(seen.size!==x.native.human.length||!p.review.citations.some(c=>c.kind==='discussion'&&c.id===r.pins.instructionId&&c.classification==='supports'))deny('EXACT_COMPLETE_REVIEW_REQUIRED');
   return db.transaction(()=>{if(!eq(registration(r.id),r)||native(r).contextRevision!==x.native.contextRevision)deny('CONTEXT_OR_TRUST_DRIFT');evidence(r,x.evidence);const end=Date.parse(p.expiresAt);if(end<=io.now()||end>Math.min(io.now()+900000,...[r.expiresAt,r.credentialExpiresAt,r.readerExpiresAt,r.custodyExpiresAt,r.acceptance.expiresAt].map(Date.parse)))deny('AUTHORITY_EXPIRY_OUT_OF_BOUNDS');const digest=actionDigest(r);if(db.prepare('SELECT 1 FROM exact_refund_authorities WHERE action_digest=? OR decision_id=?').get(digest,r.pins.decisionId))deny('PERMANENT_FINANCIAL_ACTION_FENCED');
    const a=authoritySchema.parse({schemaVersion:'exact-refund-authority/v1',authorityId:crypto.randomUUID(),revision:1,registrationId:r.id,registrationRevision:r.revision,registrationHash:canonicalSha256(r),runtimeAcceptanceHash:H('exact-refund/acceptance/v1',r.acceptance),pins:r.pins,contextRevision:x.native.contextRevision,reviewHash:H('exact-refund/review/v1',p.review),identity:identity(r),target:r.target,revisions:x.evidence.revisions,sourceEvidenceHash:x.evidence.snapshotHash,sourceCaptureAt:x.evidence.sourceCaptureAt,originalActionDigest:digest,issuedAt:iso(),expiresAt:p.expiresAt,authorityHash:'0'.repeat(64)});a.authorityHash=authorityHash(a);
    db.prepare('INSERT INTO exact_refund_authorities VALUES(?,?,?,?,?,?,?,?,?)').run(a.authorityId,digest,r.id,r.pins.decisionId,p.requestKey,requestHash,JSON.stringify(a),JSON.stringify(x.native),JSON.stringify(p.review));return {execute:false,refundEntitlement:false,authority:a,replayed:false};}).immediate();
  },
  read(a:Actor,id:string){const s=stored(id);owner(a,registration(s.a.registrationId));return {execute:false,refundEntitlement:false,authority:s.a,revoked:!!db.prepare('SELECT 1 FROM exact_refund_revocations WHERE authority_id=?').get(id),association:db.prepare('SELECT association_json FROM exact_refund_associations WHERE authority_id=?').get(id)??null};},
  revoke(a:Actor,id:string,reason:string){return db.transaction(()=>{const s=stored(id);owner(a,registration(s.a.registrationId));db.prepare('INSERT OR IGNORE INTO exact_refund_revocations VALUES(?,?,?,?)').run(id,a.user.id,reason,iso());return {execute:false,refundEntitlement:false,retryAllowed:false,reservationIrrevocable:!!db.prepare('SELECT 1 FROM exact_refund_associations WHERE authority_id=?').get(id)};}).immediate();},
  verify(reg:string,id:string){const r=registration(reg),s=current(id,r);const observedAt=iso();return {execute:false,refundEntitlement:false,retryAllowed:false,authority:s.a,observedAt,expiresAt:new Date(Math.min(Date.parse(observedAt)+15000,Date.parse(s.a.expiresAt),...[r.expiresAt,r.credentialExpiresAt,r.readerExpiresAt,r.custodyExpiresAt,r.acceptance.expiresAt].map(Date.parse))).toISOString()};},
  async associate(reg:string,raw:unknown){const p=associationInput.parse(raw),r=registration(reg),reqHash=H('exact-refund/association-request/v1',p);const prior=db.prepare('SELECT * FROM exact_refund_associations WHERE authority_id=?').get(p.authorityId) as Assoc|undefined;if(prior){if(prior.registration_id!==r.id||prior.request_hash!==reqHash)deny('ASSOCIATION_CONFLICT');return summary(prior);}
   const s=current(p.authorityId,r);if(s.a.authorityHash!==p.authorityHash)deny('AUTHORITY_HASH_MISMATCH');const i=await intent(r,p.sourceIntentId,true),b=i.binding;validateIntentBinding(r,s.a,i,true);
   if(b.authorityId!==s.a.authorityId||b.authorityHash!==s.a.authorityHash||b.originalActionDigest!==s.a.originalActionDigest||!eq(b.target,s.a.target)||!eq(b.revisions,s.a.revisions)||b.sourceEvidenceHash!==s.a.sourceEvidenceHash||i.currentEvidence.snapshotHash!==s.a.sourceEvidenceHash||b.requestKey!==p.requestKey||i.intentHash!==p.intentHash||Date.parse(b.expiresAt)>Date.parse(s.a.expiresAt))deny('AUTHORITY_INTENT_SCOPE_MISMATCH');
   return db.transaction(()=>{current(p.authorityId,registration(reg));if(!eq(registration(reg),r))deny('TRUST_DRIFT');fresh(i.observedAt,i.expiresAt);evidence(r,i.currentEvidence);if(Date.parse(b.expiresAt)<=io.now())deny('PREPARE_EXPIRED');const old=db.prepare('SELECT * FROM exact_refund_associations WHERE authority_id=?').get(p.authorityId) as Assoc|undefined;if(old){if(old.request_hash!==reqHash||old.registration_id!==r.id)deny('ASSOCIATION_CONFLICT');return summary(old);}
    const id=crypto.randomUUID(),receipt={schemaVersion:'exact-refund-association-receipt/v1',associationId:id,authorityId:s.a.authorityId,authorityHash:s.a.authorityHash,registrationId:r.id,originalActionDigest:s.a.originalActionDigest,sourceIntentId:b.sourceIntentId,requestKey:b.requestKey,intentHash:i.intentHash,reservedAt:iso(),dispatchExpiresAt:b.expiresAt};
    db.prepare('INSERT INTO exact_refund_associations VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(id,s.a.authorityId,s.a.originalActionDigest,b.sourceIntentId,r.id,r.servicePrincipalId,b.requestKey,reqHash,i.intentHash,JSON.stringify(receipt),JSON.stringify(i));return summary(readAssociation(r,id),true);}).immediate();
  },
  lookup(reg:string,raw:unknown){const r=registration(reg),p=associationInput.parse(raw);const {a}=stored(p.authorityId);if(a.registrationId!==r.id||a.authorityHash!==p.authorityHash)deny('AUTHORITY_SCOPE_CONFLICT');const rows=db.prepare('SELECT * FROM exact_refund_associations WHERE authority_id=? OR (service_principal_id=? AND (source_intent_id=? OR request_key=?))').all(p.authorityId,r.servicePrincipalId,p.sourceIntentId,p.requestKey) as Assoc[];if(rows.some(row=>row.registration_id!==r.id||row.request_hash!==H('exact-refund/association-request/v1',p)))deny('ASSOCIATION_CONFLICT');return {execute:false,refundEntitlement:false,retryAllowed:false,status:rows.length?'FOUND':'ABSENT',association:rows.length?JSON.parse(rows[0]!.association_json):null};},
  reconcile(reg:string,id:string){return summary(readAssociation(registration(reg),id));},
  async receipt(reg:string,id:string){const r=registration(reg),row=readAssociation(r,id),saved=intentSchema.parse(JSON.parse(row.intent_json)),i=await intent(r,saved.binding.sourceIntentId,false);validateIntentBinding(r,stored(row.authority_id).a,i,false);if(!eq(i.binding,saved.binding)||i.intentHash!==saved.intentHash||(i.associationId!==id&&!(i.state==='UNKNOWN'&&i.associationId===null)))deny('RECEIPT_BINDING_MISMATCH');const o=i.outcome;if(o&&(o.paymentId!==saved.binding.target.paymentId||o.amountMinor!==saved.binding.target.amountMinor||o.currency!==saved.binding.target.currency||o.providerIdempotencyKey!==saved.binding.providerIdempotencyKey||o.state!==i.state||Date.parse(o.recordedAt)>Date.parse(i.observedAt)))deny('PROVIDER_CORRELATION_MISMATCH');if(i.state==='SUCCESS'&&(!i.attemptId||!o?.refundId||o.state!=='SUCCESS'))deny('EXACT_SUCCESS_RECEIPT_REQUIRED');const state=i.state==='SUCCESS'?'SUCCESS':i.state==='ROLLED_BACK_TERMINAL'||i.state==='FAILED_TERMINAL'?i.state:'UNKNOWN';const receiptHash=H('exact-refund/receipt/v1',{associationId:id,intentHash:i.intentHash,state,attemptId:i.attemptId,outcome:o});
   return db.transaction(()=>{if(!eq(registration(reg),r))deny('TRUST_DRIFT');fresh(i.observedAt,i.expiresAt);const terminal=db.prepare("SELECT state FROM exact_refund_receipts WHERE association_id=? AND state IN ('ROLLED_BACK_TERMINAL','FAILED_TERMINAL')").get(id) as {state:string}|undefined;if(terminal&&state!==terminal.state)deny('TERMINAL_OUTCOME_CONFLICT');const success=db.prepare("SELECT receipt_json FROM exact_refund_receipts WHERE association_id=? AND state='SUCCESS'").get(id) as {receipt_json:string}|undefined;if(success&&state==='SUCCESS'&&!eq(JSON.parse(success.receipt_json).outcome,o))deny('CONFLICTING_SUCCESS_RECEIPT');db.prepare('INSERT OR IGNORE INTO exact_refund_receipts VALUES(?,?,?,?,?,?)').run(crypto.randomUUID(),id,receiptHash,state,JSON.stringify({attemptId:i.attemptId,outcome:o}),iso());return {execute:false,refundEntitlement:false,retryAllowed:false,associationId:id,state,receiptHash,noRetry:true};}).immediate();
  }
 };
}
