-- Native dependency change clock. Global invalidation is conservative; never source scope proof.
CREATE TABLE compose_context_clock(singleton INTEGER PRIMARY KEY CHECK(singleton=1),revision INTEGER NOT NULL CHECK(revision>=0));
INSERT INTO compose_context_clock VALUES(1,0);
CREATE TABLE compose_context_memberships(conversation_id TEXT NOT NULL,business_id TEXT NOT NULL,PRIMARY KEY(conversation_id,business_id));
INSERT INTO compose_context_memberships SELECT id,business_team_id FROM conversations WHERE business_team_id IS NOT NULL;
CREATE TRIGGER compose_member_insert AFTER INSERT ON conversations WHEN NEW.business_team_id IS NOT NULL BEGIN INSERT OR IGNORE INTO compose_context_memberships VALUES(NEW.id,NEW.business_team_id); END;
CREATE TRIGGER compose_member_update AFTER UPDATE OF business_team_id ON conversations WHEN NEW.business_team_id IS NOT NULL BEGIN INSERT OR IGNORE INTO compose_context_memberships VALUES(NEW.id,NEW.business_team_id); END;
CREATE TRIGGER compose_member_immutable_update BEFORE UPDATE ON compose_context_memberships BEGIN SELECT RAISE(ABORT,'Compose membership audit immutable'); END;
CREATE TRIGGER compose_member_immutable_delete BEFORE DELETE ON compose_context_memberships BEGIN SELECT RAISE(ABORT,'Compose membership audit immutable'); END;
CREATE TRIGGER compose_clock_users_insert AFTER INSERT ON users BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_users_update AFTER UPDATE ON users BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_users_delete AFTER DELETE ON users BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_business_teams_insert AFTER INSERT ON business_teams BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_business_teams_update AFTER UPDATE ON business_teams BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_business_teams_delete AFTER DELETE ON business_teams BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_business_team_members_insert AFTER INSERT ON business_team_members BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_business_team_members_update AFTER UPDATE ON business_team_members BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_business_team_members_delete AFTER DELETE ON business_team_members BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_business_bot_members_insert AFTER INSERT ON business_bot_members BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_business_bot_members_update AFTER UPDATE ON business_bot_members BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_business_bot_members_delete AFTER DELETE ON business_bot_members BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_business_delegations_insert AFTER INSERT ON business_delegations BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_business_delegations_update AFTER UPDATE ON business_delegations BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_business_delegations_delete AFTER DELETE ON business_delegations BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_business_audit_insert AFTER INSERT ON business_audit BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_business_audit_update AFTER UPDATE ON business_audit BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_business_audit_delete AFTER DELETE ON business_audit BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_conversations_insert AFTER INSERT ON conversations BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_conversations_update AFTER UPDATE ON conversations BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_conversations_delete AFTER DELETE ON conversations BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_registrations_insert AFTER INSERT ON bot_registrations BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_registrations_update AFTER UPDATE ON bot_registrations BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_registrations_delete AFTER DELETE ON bot_registrations BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_employee_workspaces_insert AFTER INSERT ON employee_workspaces BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_employee_workspaces_update AFTER UPDATE ON employee_workspaces BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_employee_workspaces_delete AFTER DELETE ON employee_workspaces BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_employee_bot_access_insert AFTER INSERT ON employee_bot_access BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_employee_bot_access_update AFTER UPDATE ON employee_bot_access BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_employee_bot_access_delete AFTER DELETE ON employee_bot_access BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_shared_bot_queues_insert AFTER INSERT ON shared_bot_queues BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_shared_bot_queues_update AFTER UPDATE ON shared_bot_queues BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_shared_bot_queues_delete AFTER DELETE ON shared_bot_queues BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_nonexclusive_bot_queues_insert AFTER INSERT ON nonexclusive_bot_queues BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_nonexclusive_bot_queues_update AFTER UPDATE ON nonexclusive_bot_queues BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_nonexclusive_bot_queues_delete AFTER DELETE ON nonexclusive_bot_queues BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_focused_workspaces_insert AFTER INSERT ON focused_workspaces BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_focused_workspaces_update AFTER UPDATE ON focused_workspaces BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_focused_workspaces_delete AFTER DELETE ON focused_workspaces BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_focused_bot_access_insert AFTER INSERT ON focused_bot_access BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_focused_bot_access_update AFTER UPDATE ON focused_bot_access BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_focused_bot_access_delete AFTER DELETE ON focused_bot_access BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_decisions_insert AFTER INSERT ON bot_decisions BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_decisions_update AFTER UPDATE ON bot_decisions BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_decisions_delete AFTER DELETE ON bot_decisions BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_decision_events_insert AFTER INSERT ON bot_decision_events BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_decision_events_update AFTER UPDATE ON bot_decision_events BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_decision_events_delete AFTER DELETE ON bot_decision_events BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_decision_threads_insert AFTER INSERT ON bot_decision_threads BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_decision_threads_update AFTER UPDATE ON bot_decision_threads BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_decision_threads_delete AFTER DELETE ON bot_decision_threads BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_discussion_instructions_insert AFTER INSERT ON bot_discussion_instructions BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_discussion_instructions_update AFTER UPDATE ON bot_discussion_instructions BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_discussion_instructions_delete AFTER DELETE ON bot_discussion_instructions BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_deferred_followups_insert AFTER INSERT ON bot_deferred_followups BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_deferred_followups_update AFTER UPDATE ON bot_deferred_followups BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_deferred_followups_delete AFTER DELETE ON bot_deferred_followups BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_human_messages_insert AFTER INSERT ON bot_human_messages BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_human_messages_update AFTER UPDATE ON bot_human_messages BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_human_messages_delete AFTER DELETE ON bot_human_messages BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_message_threads_insert AFTER INSERT ON bot_message_threads BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_message_threads_update AFTER UPDATE ON bot_message_threads BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_message_threads_delete AFTER DELETE ON bot_message_threads BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_message_replies_insert AFTER INSERT ON bot_message_replies BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_message_replies_update AFTER UPDATE ON bot_message_replies BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_message_replies_delete AFTER DELETE ON bot_message_replies BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_conversational_answers_insert AFTER INSERT ON bot_conversational_answers BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_conversational_answers_update AFTER UPDATE ON bot_conversational_answers BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_conversational_answers_delete AFTER DELETE ON bot_conversational_answers BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_message_drafts_insert AFTER INSERT ON bot_message_drafts BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_message_drafts_update AFTER UPDATE ON bot_message_drafts BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_message_drafts_delete AFTER DELETE ON bot_message_drafts BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_message_delegations_insert AFTER INSERT ON bot_message_delegations BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_message_delegations_update AFTER UPDATE ON bot_message_delegations BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_message_delegations_delete AFTER DELETE ON bot_message_delegations BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_message_delegation_events_insert AFTER INSERT ON bot_message_delegation_events BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_message_delegation_events_update AFTER UPDATE ON bot_message_delegation_events BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_message_delegation_events_delete AFTER DELETE ON bot_message_delegation_events BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_message_delivery_proofs_insert AFTER INSERT ON bot_message_delivery_proofs BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_message_delivery_proofs_update AFTER UPDATE ON bot_message_delivery_proofs BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_message_delivery_proofs_delete AFTER DELETE ON bot_message_delivery_proofs BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_message_retirements_insert AFTER INSERT ON bot_message_retirements BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_message_retirements_update AFTER UPDATE ON bot_message_retirements BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_message_retirements_delete AFTER DELETE ON bot_message_retirements BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_instruction_obligations_insert AFTER INSERT ON bot_instruction_obligations BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_instruction_obligations_update AFTER UPDATE ON bot_instruction_obligations BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_instruction_obligations_delete AFTER DELETE ON bot_instruction_obligations BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_instruction_obligation_revocations_insert AFTER INSERT ON bot_instruction_obligation_revocations BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_instruction_obligation_revocations_update AFTER UPDATE ON bot_instruction_obligation_revocations BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_instruction_obligation_revocations_delete AFTER DELETE ON bot_instruction_obligation_revocations BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_composed_sms_authorities_insert AFTER INSERT ON bot_composed_sms_authorities BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_composed_sms_authorities_update AFTER UPDATE ON bot_composed_sms_authorities BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_composed_sms_authorities_delete AFTER DELETE ON bot_composed_sms_authorities BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_composed_sms_events_insert AFTER INSERT ON bot_composed_sms_events BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_composed_sms_events_update AFTER UPDATE ON bot_composed_sms_events BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_composed_sms_events_delete AFTER DELETE ON bot_composed_sms_events BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_composed_sms_dispatch_authorities_insert AFTER INSERT ON bot_composed_sms_dispatch_authorities BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_composed_sms_dispatch_authorities_update AFTER UPDATE ON bot_composed_sms_dispatch_authorities BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_composed_sms_dispatch_authorities_delete AFTER DELETE ON bot_composed_sms_dispatch_authorities BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_composed_sms_associations_insert AFTER INSERT ON bot_composed_sms_associations BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_composed_sms_associations_update AFTER UPDATE ON bot_composed_sms_associations BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_composed_sms_associations_delete AFTER DELETE ON bot_composed_sms_associations BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_composed_sms_service_receipts_insert AFTER INSERT ON bot_composed_sms_service_receipts BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_composed_sms_service_receipts_update AFTER UPDATE ON bot_composed_sms_service_receipts BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_composed_sms_service_receipts_delete AFTER DELETE ON bot_composed_sms_service_receipts BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_routine_policies_insert AFTER INSERT ON bot_routine_policies BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_routine_policies_update AFTER UPDATE ON bot_routine_policies BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_routine_policies_delete AFTER DELETE ON bot_routine_policies BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_routine_policy_revocations_insert AFTER INSERT ON bot_routine_policy_revocations BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_routine_policy_revocations_update AFTER UPDATE ON bot_routine_policy_revocations BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_bot_routine_policy_revocations_delete AFTER DELETE ON bot_routine_policy_revocations BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_routine_source_trust_insert AFTER INSERT ON routine_source_trust BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_routine_source_trust_update AFTER UPDATE ON routine_source_trust BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_routine_source_trust_delete AFTER DELETE ON routine_source_trust BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_routine_source_revocations_insert AFTER INSERT ON routine_source_revocations BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_routine_source_revocations_update AFTER UPDATE ON routine_source_revocations BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_routine_source_revocations_delete AFTER DELETE ON routine_source_revocations BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_routine_source_proofs_insert AFTER INSERT ON routine_source_proofs BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_routine_source_proofs_update AFTER UPDATE ON routine_source_proofs BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_routine_source_proofs_delete AFTER DELETE ON routine_source_proofs BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_routine_draft_authorizations_insert AFTER INSERT ON routine_draft_authorizations BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_routine_draft_authorizations_update AFTER UPDATE ON routine_draft_authorizations BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_routine_draft_authorizations_delete AFTER DELETE ON routine_draft_authorizations BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_routine_draft_claims_insert AFTER INSERT ON routine_draft_claims BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_routine_draft_claims_update AFTER UPDATE ON routine_draft_claims BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_routine_draft_claims_delete AFTER DELETE ON routine_draft_claims BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_routine_dispatch_claims_insert AFTER INSERT ON routine_dispatch_claims BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_routine_dispatch_claims_update AFTER UPDATE ON routine_dispatch_claims BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_routine_dispatch_claims_delete AFTER DELETE ON routine_dispatch_claims BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_routine_delivery_readbacks_insert AFTER INSERT ON routine_delivery_readbacks BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_routine_delivery_readbacks_update AFTER UPDATE ON routine_delivery_readbacks BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_routine_delivery_readbacks_delete AFTER DELETE ON routine_delivery_readbacks BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_routine_scope_evidence_insert AFTER INSERT ON routine_scope_evidence BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_routine_scope_evidence_update AFTER UPDATE ON routine_scope_evidence BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_routine_scope_evidence_delete AFTER DELETE ON routine_scope_evidence BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_routine_hold_bindings_insert AFTER INSERT ON routine_hold_bindings BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_routine_hold_bindings_update AFTER UPDATE ON routine_hold_bindings BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_routine_hold_bindings_delete AFTER DELETE ON routine_hold_bindings BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_routine_hold_revocations_insert AFTER INSERT ON routine_hold_revocations BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_routine_hold_revocations_update AFTER UPDATE ON routine_hold_revocations BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_routine_hold_revocations_delete AFTER DELETE ON routine_hold_revocations BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_routine_scope_handoffs_insert AFTER INSERT ON routine_scope_handoffs BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_routine_scope_handoffs_update AFTER UPDATE ON routine_scope_handoffs BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_routine_scope_handoffs_delete AFTER DELETE ON routine_scope_handoffs BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_routine_scope_handoff_revocations_insert AFTER INSERT ON routine_scope_handoff_revocations BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_routine_scope_handoff_revocations_update AFTER UPDATE ON routine_scope_handoff_revocations BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_routine_scope_handoff_revocations_delete AFTER DELETE ON routine_scope_handoff_revocations BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_routine_scope_handoff_evidence_insert AFTER INSERT ON routine_scope_handoff_evidence BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_routine_scope_handoff_evidence_update AFTER UPDATE ON routine_scope_handoff_evidence BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;
CREATE TRIGGER compose_clock_routine_scope_handoff_evidence_delete AFTER DELETE ON routine_scope_handoff_evidence BEGIN UPDATE compose_context_clock SET revision=revision+1 WHERE singleton=1; END;

-- Mutable ordinary drafts can be deleted by cascading conversation removal. Preserve
-- unresolved coverage instead of allowing fresh inventory to interpret deletion as clearance.
CREATE TABLE compose_context_deleted_drafts(id INTEGER PRIMARY KEY,draft_id TEXT NOT NULL,business_id TEXT NOT NULL,prior_json TEXT NOT NULL);
CREATE TRIGGER compose_deleted_draft BEFORE DELETE ON bot_message_drafts BEGIN
 INSERT INTO compose_context_deleted_drafts(draft_id,business_id,prior_json)
 SELECT OLD.id,business_id,json_object('id',OLD.id,'conversation_id',OLD.conversation_id,'version',OLD.version,'state',OLD.state,'payload_json',OLD.payload_json,'receipt',OLD.receipt,'claim_key',OLD.claim_key)
 FROM compose_context_memberships WHERE conversation_id=OLD.conversation_id;
END;
CREATE TRIGGER compose_deleted_draft_no_update BEFORE UPDATE ON compose_context_deleted_drafts BEGIN SELECT RAISE(ABORT,'Deleted draft coverage immutable'); END;
CREATE TRIGGER compose_deleted_draft_no_delete BEFORE DELETE ON compose_context_deleted_drafts BEGIN SELECT RAISE(ABORT,'Deleted draft coverage immutable'); END;
