import type {ConversationDiscoveryToolDefinition} from './conversationDiscoveryTools.js';
const str={type:'string'},yes={const:true},array=(items:unknown)=>({type:'array',items});
const object=(properties:Record<string,unknown>,optional:string[]=[])=>({type:'object',properties,required:Object.keys(properties).filter(k=>!optional.includes(k)),additionalProperties:false});
const citation=object({kind:{enum:['direct_message','result_reply','decision_discussion','voice_dispatch']},id:str,text:str});
const scope=object({executor_conversation_id:str,channel:{const:'email'},account:str,recipient:str,thread_id:str,in_reply_to:str,subject:str,body:str,attachments:array(object({name:str,path:str,sha256:str}))});
const input={source_kind:{enum:['direct_message','result_reply']},source_id:str,scope};
const review=object({reviewed_full_context:yes,interpretation:{const:'unconditional_compose_and_send'},instruction:citation,explanation:str,scope_explanation:str,later_context:array(object({citation,classification:{enum:['unrelated','status_only','supersedes','ambiguous']},explanation:str})),records:array(object({kind:{enum:['draft','decision']},id:str,classification:{enum:['unrelated','same_reply_unapproved','blocking']},explanation:str})),body_parts:array(object({start:{type:'integer'},end:{type:'integer'},human_ids:array(str),evidence:str})),unresolved_choices:{type:'array',items:str,maxItems:0}});
const source_check=object({observed_at:str,payload_hash:str,account_thread_recipient_verified:yes,permissions_verified:yes,attachments_verified:yes,no_prior_or_uncertain_send:yes,exclusive_source_ownership:yes,evidence:str});
const define=(name:string,description:string,properties:Record<string,unknown>,optional:string[]=[]):ConversationDiscoveryToolDefinition=>({name,description,inputSchema:object(properties,optional)});
export const VENDOR_EMAIL_TOOLS=[
 define('read_vendor_email_context','Original registered executor only: discover exact authenticated own-chat human source IDs and read complete native direct messages, result anchors, shared voice dispatches, decisions and drafts before preparing the exact vendor reply. No authority, send or caller-private voice access. A forwarded direction is not an authenticated direct-message ID.',{}),
 define('inspect_vendor_email','Original registered bot only: inspect a prospective vendor EMAIL reply against exact authenticated own-chat human source. Read complete native human context, result anchors, drafts and decisions; inspect media and current mailbox through your existing access. Supply exact account, one recipient, thread, replied-to message, full subject/body and retained attachment SHA256. No send, authority, draft mutation or source access is granted. A handoff or bot report is not human provenance. A source already consumed by a native decision must retain that approval path and named executor. Missing exact source stays blocked; do not request duplicate approval or use raw Gmail to bypass.',input),
 define('bind_vendor_email','Original executor only: prospective native binding after inspect_vendor_email and semantic full-context review of unconditional compose AND send direction. Supply full exact instruction, every later human citation/classification, every draft/decision assessment, contiguous body support, scope explanation and fresh truthful source checks within five minutes. Status, quotations, wording edits, conditions, holds and ambiguity do not authorize. Preserve old ordinary drafts/decisions. Use stable request_key. An unclaimed correction needs exact current supersedes_id and fresh supported scope; recipients cannot expand. One human source may bind only one thread. Bind never sends.',{...input,inspection_hash:str,review,source_check,request_key:str,supersedes_id:str},['supersedes_id']),
 define('read_vendor_email','Read your exact native vendor-email authority, active target and immutable attempt/receipt history. Always execute:false. Read this after a lost bind/claim/delivery response; no new key, authority or replay can recover another send attempt.',{authority_id:str}),
 define('claim_vendor_email','Original executor only: inspect the SAME bound scope/source again and submit current full semantic review, inspection_hash and truthful fresh permissions/source/account/recipient/thread/attachment/exclusive-owner/duplicate checks. Only the FIRST execute:true response permits ONE exact send using existing authorized Gmail access, with returned idempotency key. No transport or financial authority is granted. Repeated claims return execute:false; UNKNOWN, failure, replacement or new keys never free the thread. Recheck exact source and bytes immediately before dispatch. No automated retry.',{authority_id:str,claim_key:str,inspection_hash:str,review,source_check}),
 define('record_vendor_email_delivery','Original claiming executor only. Record verified Gmail provider acceptance (not delivery) with exact provider message/account/recipient/thread/replied-to message/payload hash/idempotency proof; reconcile uncertainty read-only. This is accountable executor source readback, not server-authenticated Gmail proof. Uncertain or failed records never release the attempt or permit resending. Keep stable request_key; no fabricated receipts. No business decision is completed by this call.',{authority_id:str,claim_key:str,request_key:str,state:{enum:['sent','uncertain','failed']},evidence:str,proof:object({provider:{const:'gmail'},provider_message_id:str,account:str,recipient:str,thread_id:str,in_reply_to:str,payload_hash:str,idempotency_key:str,verified:yes})},['proof']),
 define('revoke_vendor_email','Original executor only: append revocation of this authority without removing history or releasing any source/thread fence. Revocation before claim blocks sending; after claim it cannot cancel an external attempt or enable another one. Use read_vendor_email to reconcile.',{authority_id:str,request_key:str,reason:str}),
];
