import Database from 'better-sqlite3';
import {it,expect} from 'vitest';
import {reserveComposeLineage,readComposeLineage} from '../src/bots/composedSmsLineage.js';
import {originalActionDigest} from '../src/bots/composedSmsCorrectionContract.js';
const business='00000000-0000-4000-8000-000000000001',decision='00000000-0000-4000-8000-000000000002',action='00000000-0000-4000-8000-000000000003',id='00000000-0000-4000-8000-000000000004';
function fixture(){const db=new Database(':memory:');db.exec('CREATE TABLE bot_composed_sms_authorities(id TEXT PRIMARY KEY, action_id TEXT UNIQUE, snapshot_json TEXT); CREATE TABLE bot_composed_sms_dispatch_authorities(authority_id TEXT PRIMARY KEY,action_id TEXT UNIQUE,tuple_json TEXT); CREATE TABLE compose_action_lineages(original_action_digest TEXT PRIMARY KEY,native_action_id TEXT UNIQUE,business_id TEXT,decision_id TEXT,authority_id TEXT UNIQUE);');return db;}
it('adopts historical dispatch UUID exactly, never generates a replacement after UNKNOWN or expiry',()=>{const db=fixture();try{db.prepare('INSERT INTO bot_composed_sms_authorities VALUES(?,?,?)').run(id,originalActionDigest(business,decision),JSON.stringify({binding:{business_id:business},native:{existing_consumption:{decision_id:decision}}}));db.prepare('INSERT INTO bot_composed_sms_dispatch_authorities VALUES(?,?,?)').run(id,action,JSON.stringify({nativeActionId:action,authorityId:id,businessId:business}));expect(readComposeLineage(db,action,'https://native.example.invalid').nativeActionId).toBe(action);expect(db.prepare('SELECT count(*) n FROM compose_action_lineages').get()).toEqual({n:0});expect(reserveComposeLineage(db,id).native_action_id).toBe(action);expect(reserveComposeLineage(db,id).native_action_id).toBe(action);expect(()=>db.prepare('INSERT INTO bot_composed_sms_authorities VALUES(?,?,?)').run('copy',originalActionDigest(business,decision),'{}')).toThrow();expect(()=>readComposeLineage(db,decision,'https://native.example.invalid')).toThrow('Exact durable');}finally{db.close();}});
it('denies conflicting historical mapping without silently repairing it',()=>{const db=fixture();try{db.prepare('INSERT INTO bot_composed_sms_authorities VALUES(?,?,?)').run(id,originalActionDigest(business,decision),JSON.stringify({binding:{business_id:business},native:{existing_consumption:{decision_id:decision}}}));db.prepare('INSERT INTO bot_composed_sms_dispatch_authorities VALUES(?,?,?)').run(id,action,JSON.stringify({nativeActionId:action,authorityId:id,businessId:business}));db.prepare('INSERT INTO compose_action_lineages VALUES(?,?,?,?,?)').run(originalActionDigest(business,decision),decision,business,decision,id);expect(()=>reserveComposeLineage(db,id)).toThrow('conflicting');expect(()=>readComposeLineage(db,action,'https://native.example.invalid')).toThrow('Conflicting');}finally{db.close();}});
// Executable protocol model only: not a claim about source PostgreSQL writers.
// Both source tables must be inventoried under the same common serialization gate.
it.each(['intent','audit'])('source adoption model includes %s-only historical rows and detects concurrent legacy preparation',kind=>{const db=new Database(':memory:');try{
 db.exec('CREATE TABLE intents(action TEXT PRIMARY KEY, revision INTEGER);CREATE TABLE audits(action TEXT PRIMARY KEY,revision INTEGER);CREATE TABLE mappings(action TEXT PRIMARY KEY,digest TEXT UNIQUE);');const table=kind==='intent'?'intents':'audits';db.prepare('INSERT INTO '+table+' VALUES(?,1)').run(action);
 const inventory=()=>JSON.stringify({intents:db.prepare('SELECT * FROM intents ORDER BY action').all(),audits:db.prepare('SELECT * FROM audits ORDER BY action').all()});const observed=inventory();
 // A legacy writer commits while the adapter performs authenticated lineage GET.
 db.prepare('INSERT INTO intents VALUES(?,1)').run(id);
 const adopt=(snapshot:string,lineages:Map<string,string>)=>db.transaction(()=>{if(inventory()!==snapshot)throw Error('complete revision inventory changed');const rows=db.prepare('SELECT action FROM intents UNION SELECT action FROM audits').all() as {action:string}[];for(const row of rows){const digest=lineages.get(row.action);if(!digest)throw Error('unresolved historical lineage');db.prepare('INSERT INTO mappings VALUES(?,?)').run(row.action,digest);}}).immediate();
 expect(()=>adopt(observed,new Map([[action,'same-action']]))).toThrow('changed');expect(()=>adopt(inventory(),new Map([[id,'other']]))).toThrow('unresolved');expect(()=>adopt(inventory(),new Map([[action,'same-action'],[id,'same-action']]))).toThrow();expect(db.prepare('SELECT count(*) n FROM mappings').get()).toEqual({n:0});adopt(inventory(),new Map([[action,'a'],[id,'b']]));expect(db.prepare('SELECT count(*) n FROM mappings').get()).toEqual({n:2});
 }finally{db.close();}});
