import {CORRECTION_DISPATCH,correctionBindingHash,verifyCorrectionDispatch,correctionEnvelopeSchema} from '../src/bots/composedSmsCorrectionContract.js';
import {correctionPreflight} from '../src/bots/correctionPreflight.js';
import {composeHash} from '../src/bots/composedSmsContract.js';
import {composedSmsScope} from '../src/bots/composedSmsScope.js';
import {reserveComposeLineage,readComposeLineage} from '../src/bots/composedSmsLineage.js';
import fs from 'node:fs';
import {composedSmsCorrectionV2,correctionReviewSchema,verifyCorrectionAuthority} from '../src/bots/composedSmsCorrectionV2.js';
import {fixtureCredentialExpiry} from './composeGuardFixture.js';
import {fixtureGuards} from './composeGuardFixture.js';
import {composedSmsVerifier} from '../src/bots/composedSmsVerifier.js';
import {bindingHash,type ComposeAuthority} from '../src/bots/composedSmsContract.js';
import type {ComposeRegistration} from '../src/bots/composedSmsTrust.js';
import {communicationService} from '../src/bots/communication.js';
import Database from 'better-sqlite3';
import {beforeEach,afterEach,it,expect,vi} from 'vitest';
import {fileURLToPath} from 'node:url';
import {migrate} from '../src/db/migrate.js';
import {createBotService,type Actor} from '../src/bots/service.js';
import {captureHumanMessage} from '../src/bots/humanMessages.js';
import {composedSmsService,type CompositionEvidence,type ComposedInput} from '../src/bots/composedSms.js';
import {canonicalSha256} from '../src/bots/canonical.js';
import type {UserRow} from '../src/db/db.js';
const ids={owner:'10000000-0000-4000-8000-000000000001',executor:'10000000-0000-4000-8000-000000000002',other:'10000000-0000-4000-8000-000000000003',business:'20000000-0000-4000-8000-000000000001',canonical:'30000000-0000-4000-8000-000000000001',contact:'30000000-0000-4000-8000-000000000002'};
let db:Database.Database,owner:Actor,executor:Actor,human:Actor,s:ReturnType<typeof composedSmsService>,bots:ReturnType<typeof createBotService>,source:string,composition:string,decision:string,evidence:CompositionEvidence,clock:number,allow=true;
const body='Please send photos of what arrived and what is missing.';
const payload={channel:'sms',account:'Synthetic SMS +12025550100',recipients:['+12025550111'],subject:'',body,attachments:[],customer:'Synthetic person',ticket:'PHONE',context:'Reference only'};
const input=():ComposedInput=>({source_id:source,draft_id:'draft',expected_draft_version:1,executor_conversation_id:ids.executor,canonical_case:ids.canonical,contact_case:ids.contact});
const review=()=>({mode:'compose_and_send' as const,reviewed_full_context:true as const,recipient_instruction:{id:composition,text:'Ask for photos of what arrived and what is missing. Reply to +12025550111.'},composition_instruction:{id:composition,text:'Ask for photos of what arrived and what is missing. Reply to +12025550111.'},channel_instruction:{id:source,text:'Send the email and SMS as well.'},purpose:'Obtain photos and missing-parts description',relationship_explanation:'Customer messages identify the same request and specific phone, not a merged customer record',customer_message_ids:['email','sms'],parts:[{start:0,end:body.length,assessment:'supported' as const,human_ids:[composition],message_ids:['email','sms'],explanation:'Implements the bounded request without a remedy or new commitment'}],unresolved_choices:[]});
beforeEach(()=>{
 db=new Database(':memory:');migrate(db,fileURLToPath(new URL('../src/db/migrations',import.meta.url)));
 db.prepare("INSERT INTO users(id,email,display_name,role) VALUES(1,'fixture@test','Human','owner')").run();db.prepare('INSERT INTO business_teams(id,name,owner_id) VALUES(?,?,1)').run(ids.business,'Fixture');
 for(const c of [ids.owner,ids.executor,ids.other]){db.prepare("INSERT INTO conversations(id,assistant_id,user_id,title,provider,native_session_id,visibility,business_team_id) VALUES(?,1,1,?,'codex',?,'team',?)").run(c,c,c,ids.business);db.prepare('INSERT INTO bot_registrations(conversation_id,name,active,registered_by) VALUES(?,?,1,1)').run(c,c);}
 human={user:db.prepare('SELECT * FROM users WHERE id=1').get() as UserRow};owner={...human,conversationId:ids.owner};executor={...human,conversationId:ids.executor};bots=createBotService(db);
 decision=bots.raise(owner,{source_key:'case',proposal_key:'email',proposal:{question:'Send exact email?',recommendation:'Photos',consequence:'Customer reply',blocked_action:'Only this email',assignee_id:1,evidence:[],message_delivery:{canonical_case:ids.canonical,executor_conversation_id:ids.owner,payload:{...payload,channel:'email',account:'fixture@example.test',recipients:['customer@example.test'],ticket:'EMAIL'}}}}).id;
 vi.useFakeTimers(); vi.setSystemTime(Date.now()-2000);
 composition=captureHumanMessage(db,ids.owner,1,'Ask for photos of what arrived and what is missing. Reply to +12025550111.');vi.setSystemTime(Date.now()+1000);source=captureHumanMessage(db,ids.owner,1,'Send the email and SMS as well.');
 vi.useRealTimers();
 const ci=bots.inspectConversationalDecision(owner,decision,1,'direct_message',source);bots.recordConversationalDecision(owner,decision,1,'direct_message',source,ci.inspection_hash!,'approve',true);
 db.prepare("INSERT INTO bot_message_drafts(id,conversation_id,request_key,payload_json,created_at) VALUES('draft',?,'ordinary',?,'2099-01-01 00:00:00')").run(ids.executor,JSON.stringify(payload));
 clock=Date.now();allow=true;
 evidence={projection:{cases:[{id:ids.canonical,ticketNumber:'EMAIL',customerId:'customer-one',relatedOrderId:null,customer:{phone:null}},{id:ids.contact,ticketNumber:'PHONE',customerId:'customer-two',relatedOrderId:null,customer:{phone:payload.recipients[0]!}}],messages:[{id:'email',conversationId:ids.canonical,direction:'inbound',channel:'email',messageType:'message',body:'Order fixture, my phone is +12025550111.',fromPhone:null,actorType:null,actorId:null,agentId:null,aiGenerated:false},{id:'sms',conversationId:ids.contact,direction:'inbound',channel:'sms',messageType:'message',body:'Same order fixture.',fromPhone:payload.recipients[0]!,actorType:null,actorId:null,agentId:null,aiGenerated:false}]},snapshot_hash:'a'.repeat(64),registration_hash:'b'.repeat(64),business_id:ids.business,account_id:'source-account',principal_id:'fixture',sms_account:payload.account,sender_phone:'+12025550100',sender_verified:true,dispatch:{supported:true,contract:'native-compose-sms/v1',revision:'fixture-accepted-transport',reason:'Synthetic fenced transport only'},assertFresh(){if(!allow)throw Error('Source authority revoked');}};
 const reg:ComposeRegistration={registrationId:'40000000-0000-4000-8000-000000000001',revision:1,active:true,businessId:ids.business,businessOwnerUserId:1,sourceOrigin:'https://orderops-dev-web-production.up.railway.app',runtime:{projectId:ids.business,environmentId:ids.canonical,serviceId:ids.contact},sourceRegistrationHash:'c'.repeat(64),sourceAccountId:evidence.account_id,servicePrincipalId:'dedicated-fixture',serviceCredentialHash:'d'.repeat(64),nativeAudience:'dedicated-fixture-audience',cfClientId:'dedicated-fixture-client',capabilities:['compose.authority.read','compose.permit.redeem','compose.association.read'],executorBindings:[{conversationId:ids.executor,userId:1,principalId:'executor-fixture'}],senderReceiptIssuerId:'fixture-issuer',guardContractHash:'e'.repeat(64),expiresAt:new Date(clock+3600000).toISOString(),credentialExpiry:fixtureCredentialExpiry(),custodyReceipt:'synthetic-only',readbackCredential:{project:'fixture',config:'test',name:'DEDICATED_READBACK'},readbackCustodyReceipt:'synthetic-only'};
 fixtureGuards(reg);
 evidence.dispatch_material_hash='f'.repeat(64);
 evidence.boundary={registration:reg,materialHash:'f'.repeat(64),sender:{receiptId:'50000000-0000-4000-8000-000000000001',revision:1,issuerId:'fixture-issuer',providerAccountId:'AC'+'a'.repeat(32),fromPhone:evidence.sender_phone,expiresAt:new Date(clock+3600000).toISOString()},guardContractHash:reg.guardContractHash,assertFresh:()=>evidence.assertFresh()};
 s=composedSmsService(db,async()=>evidence,()=>clock);
});
afterEach(()=>{vi.useRealTimers();db.close();});

let correction:string;
const correctedBody='Please reply with a photo of the unit you received.';
const correctedPayload={...payload,body:correctedBody};
const direction='Please compose and send the corrected SMS asking only for a photo of the unit received to +12025550111. Use the same account and executor.';
beforeEach(()=>{
 db.prepare("UPDATE bot_message_drafts SET created_at=? WHERE id='draft'").run(new Date(Date.now()-500).toISOString());
 vi.useFakeTimers();vi.setSystemTime(Date.now()+1000);correction=captureHumanMessage(db,ids.owner,1,direction);vi.useRealTimers();
 const proposal=JSON.parse((db.prepare('SELECT proposal_json FROM bot_decisions WHERE id=?').get(decision) as {proposal_json:string}).proposal_json);
 bots.revise(owner,decision,1,'corrected',{...proposal,recommendation:'Photo only',message_delivery:{...proposal.message_delivery,payload:{...proposal.message_delivery.payload,body:correctedBody}}});
 db.prepare("INSERT INTO bot_message_drafts(id,conversation_id,request_key,payload_json) VALUES('corrected',?,'corrected',?)").run(ids.executor,JSON.stringify(correctedPayload));
});
const corrections=()=>composedSmsCorrectionV2(db,async()=>evidence,()=>clock);
const correctionInput=()=>({...input(),draft_id:'corrected',decision_id:decision,expected_decision_version:2,lineage_draft_id:'draft',correction_source_kind:'direct_message' as const,correction_source_id:correction});
const correctionReview=()=>({...review(),instruction_kind:'compose_and_send' as const,correction_instruction:{id:correction,text:direction},send_instruction:{id:correction,text:direction},composition_instruction:{id:correction,text:direction},channel_instruction:{id:correction,text:direction},interpretation:'Human explicitly directs a bounded corrected composition and sending, without another business choice.',parts:[{start:0,end:correctedBody.length,assessment:'supported' as const,human_ids:[correction],message_ids:['email','sms'],explanation:'Only the photo request explicitly directed by the correction.'}]});

beforeEach(()=>{
 const r=evidence.boundary!.registration;r.executorBindings[0]!.principalId='veneer:'+ids.executor;
 r.correctionAcceptance={schemaVersion:'compose-correction-acceptance/v1',nativeIssuer:'https://native.example.invalid',sourceRegistrationHash:r.sourceRegistrationHash,contractHash:'6457641ca5d576fbd43c7828e1da6d4e81af84549ac0b0c67b8f5ef1914b1479',sourceImplementationHash:'a'.repeat(64),lineageAdoptionReceiptHash:'b'.repeat(64),custodyAmendmentHash:'c'.repeat(64),reviewedBy:ids.owner,receipt:'synthetic-only',reviewedAt:new Date(clock-10000).toISOString(),expiresAt:r.expiresAt,capabilities:['compose.correction.read','compose.lineage.read','compose.correction.associate','compose.correction.readback','compose.correction.scope']};
 r.guardManifest!.nativeContextContract='compose-sms-current-context/v2';r.guardContractHash=composeHash('compose-sms-guards/v1',r.guardManifest);r.guardAcceptance!.manifestHash=r.guardContractHash;evidence.boundary!.guardContractHash=r.guardContractHash;
 evidence.dispatch.contract=CORRECTION_DISPATCH;
 // Scope fixture marks only the exact current action's structured decision as
 // disjoint for this test. Production scope completeness is unchanged.
 s=composedSmsService(db,async a=>({...evidence,principal_id:a.conversationId===ids.executor?'veneer:'+ids.executor:evidence.principal_id}),()=>clock);
});
function later(text='So you sent that?'){vi.useFakeTimers();vi.setSystemTime(Date.now()+2000);const id=captureHumanMessage(db,ids.owner,1,text);vi.useRealTimers();return id;}
async function correctionRequest(){
 const p=correctionInput(),i=await corrections().inspect(owner,p),preflight=i.preflight;
 return {...p,inspection_hash:i.inspection_hash!,request_key:'correction',review:{...correctionReview(),send_instruction:review().channel_instruction,channel_instruction:review().channel_instruction},continuity:{kind:'narrowing_continuing_compose_and_send' as const,explanation:'The current correction narrows the original unconditional compose and send direction without a new substantive choice.'},context_review:{decision_id:decision,expected_version:2,original_source_id:source,correction_source_kind:'direct_message' as const,correction_source_id:correction,inspection_hash:preflight.inspection_hash,reviewed_full_context:true as const,correction:{kind:'direct_message' as const,id:correction,text:direction},interpretation:'compose_and_send_direction' as const,explanation:'The complete context retains ongoing compose and send direction narrowed by the photo correction.',later_context:preflight.later_human_context.map(x=>({citation:{kind:x.kind,id:x.id,text:x.text},classification:'status_only' as const,explanation:'This is only a delivery status question and gives no new direction.'}))}};
}
async function derive(){const p=await correctionRequest();return corrections().derive(owner,p);}
const check=()=>({payload_hash:canonicalSha256(correctedPayload),material_evidence_unchanged:true,recipient_account_case_verified:true,lease_and_duplicates_checked:true,evidence:'Synthetic current checks only'});
function verifier(readback:()=>unknown){const r=evidence.boundary!.registration;const scope=composedSmsScope(db,()=>r,async()=>{throw Error('No source scope fixture supplied');},id=>s.serviceCurrent(id),()=>clock);return composedSmsVerifier(db,{registration:()=>r,nativeCurrent:s.serviceCurrent,now:()=>clock,scope,readback:async()=>readback()});}
it('integrates full status-context review, prospective derivation, hashes-only export and correction-aware context without old consumption validation',async()=>{
 later();const tables=['bot_decisions','bot_decision_events','bot_conversational_answers','bot_message_drafts','bot_human_messages'],before=tables.map(t=>db.prepare('SELECT * FROM '+t).all());
 const g=await derive();expect(g.authority!.schemaVersion).toBe('native-compose-sms-correction/v2');expect(g.execute).toBe(false);expect(tables.map(t=>db.prepare('SELECT * FROM '+t).all())).toEqual(before);
 const v=verifier(()=>null),r=evidence.boundary!.registration,a=v.correctionAuthority(r.registrationId,g.authority_id,1,g.native_action_id!);
 expect(correctionEnvelopeSchema.parse(a)).toEqual(a);expect(JSON.stringify(a)).not.toContain(direction);expect(JSON.stringify(a)).not.toContain('So you sent that?');expect(a.authority.payloadHash).toBe(canonicalSha256(correctedPayload));expect(a.lineage.originalActionDigest).toBe(g.action_id);
 expect(()=>v.authority(r.registrationId,g.authority_id,1,g.native_action_id!)).toThrow('UNAVAILABLE');
 const context=await v.currentContextV2(r.registrationId,g.authority_id,1,g.native_action_id!);expect(context.execute).toBe(false);expect(context.blockingIds.length).toBeGreaterThan(0);
 await s.accept(executor,g.authority_id,'accept',canonicalSha256(correctedPayload));const claim=await s.claim(executor,g.authority_id,'claim',check());expect(claim.execute).toBe(false);expect(claim.reservation).not.toBeNull();
 const repeat=await s.claim(executor,g.authority_id,'other-key',check());expect(repeat.reservation).toEqual(claim.reservation);
});
it.each(['wording_edit_only','status_only','quoted_or_reported','conditional','ambiguous'] as const)('does not convert %s assessment to authority',async interpretation=>{const p=await correctionRequest();await expect(corrections().derive(owner,{...p,context_review:{...p.context_review,interpretation}})).rejects.toThrow('direction');});
it('denies omitted/forged later citations, supersession and status cited as consent',async()=>{const status=later(),p=await correctionRequest();for(const context_review of [{...p.context_review,later_context:[]},{...p.context_review,later_context:p.context_review.later_context.map(x=>({...x,classification:'substantive_supersession'}))},{...p.context_review,correction:{...p.context_review.correction,text:'forged'}}])await expect(corrections().derive(owner,{...p,context_review})).rejects.toThrow();await expect(corrections().derive(owner,{...p,review:{...p.review,send_instruction:{id:status,text:'So you sent that?'}}})).rejects.toThrow('status');});
it.each(['body','recipients','account','channel','customer','ticket','version'] as const)('denies corrected %s drift',async field=>{const p=await correctionRequest();if(field==='version')db.prepare("UPDATE bot_message_drafts SET version=2 WHERE id='corrected'").run();else db.prepare("UPDATE bot_message_drafts SET payload_json=? WHERE id='corrected'").run(JSON.stringify({...correctedPayload,[field]:field==='recipients'?['+12025550999']:'changed'}));await expect(corrections().derive(owner,p)).rejects.toThrow();});
it.each(['owner','executor','human','source','sender','material'] as const)('denies %s revocation/drift',async kind=>{const p=await correctionRequest();if(kind==='owner'||kind==='executor')db.prepare('UPDATE bot_registrations SET active=0 WHERE conversation_id=?').run(kind==='owner'?ids.owner:ids.executor);if(kind==='human')db.prepare("UPDATE users SET status='disabled' WHERE id=1").run();if(kind==='source')allow=false;if(kind==='sender')evidence.sender_verified=false;if(kind==='material')evidence.dispatch_material_hash='0'.repeat(64);await expect(corrections().derive(owner,p)).rejects.toThrow();});
it('revalidates after awaited source read and in immediate transaction',async()=>{const p=await correctionRequest();const changed=composedSmsCorrectionV2(db,async()=>{db.prepare('UPDATE bot_decisions SET handling_revision=handling_revision+1 WHERE id=?').run(decision);return evidence;},()=>clock);await expect(changed.derive(owner,p)).rejects.toThrow('changed');expect(db.prepare('SELECT count(*) n FROM bot_composed_sms_authorities').get()).toEqual({n:0});});
it('fences copied drafts, new keys, UNKNOWN, expired and revoked authorities on the same original action',async()=>{const p=await correctionRequest(),g=await corrections().derive(owner,p);expect((await corrections().derive(owner,p)).replayed).toBe(true);db.prepare("INSERT INTO bot_message_drafts(id,conversation_id,request_key,payload_json) VALUES('copy',?,'copy',?)").run(ids.executor,JSON.stringify(correctedPayload));const q={...correctionInput(),draft_id:'copy'},i=await corrections().inspect(owner,q);await expect(corrections().derive(owner,{...p,...q,inspection_hash:i.inspection_hash!,request_key:'new'})).rejects.toThrow('reserved');s.revoke(owner,g.authority_id,'revoke','Withdrawn synthetic authority');clock+=3600001;expect((await s.claim(executor,g.authority_id,'claim',check()).catch(e=>e)).status).toBeDefined();expect(db.prepare('SELECT count(*) n FROM compose_action_lineages').get()).toEqual({n:1});expect(()=>db.prepare('DELETE FROM compose_action_lineages').run()).toThrow('permanent');});
it('keeps new routes unavailable with old protected trust and no amendment',async()=>{delete evidence.boundary!.registration.correctionAcceptance;await expect(derive()).rejects.toThrow('UNAVAILABLE');expect(db.prepare('SELECT count(*) n FROM bot_composed_sms_dispatch_authorities').get()).toEqual({n:0});expect(db.prepare('SELECT count(*) n FROM bot_composed_sms_authorities').get()).toEqual({n:0});});
it('rejects wrong owner, executor or original lineage and does not fetch on native failure',async()=>{await expect(corrections().inspect(executor,correctionInput())).rejects.toThrow();await expect(corrections().inspect(owner,{...correctionInput(),executor_conversation_id:ids.other})).rejects.toThrow();await expect(corrections().inspect(owner,{...correctionInput(),source_id:correction})).rejects.toThrow();});
it('permanently serializes simultaneous copied requests into one native UUID',async()=>{const p=await correctionRequest(),results=await Promise.allSettled([corrections().derive(owner,p),corrections().derive(owner,{...p,request_key:'competitor'})]);expect(results.filter(x=>x.status==='fulfilled')).toHaveLength(1);const g=(results.find(x=>x.status==='fulfilled') as PromiseFulfilledResult<any>).value;expect(reserveComposeLineage(db,g.authority_id).native_action_id).toBe(g.native_action_id);expect(readComposeLineage(db,g.native_action_id,'https://native.example.invalid').originalActionDigest).toBe(g.action_id);});
// Isolated accepted-scope adapter models a source/native scope review contract.
// The separate real-context test above proves actual unknown inventory blocks;
// this fixture is not evidence that any real case can be scoped unrelated.
async function dispatchFixture(){
 later();const g=await derive(),r=evidence.boundary!.registration;await s.accept(executor,g.authority_id,'accept',canonicalSha256(correctedPayload));const claim=await s.claim(executor,g.authority_id,'claim',check()),c=claim.reservation;
 const a=verifyCorrectionDispatch(JSON.parse((db.prepare('SELECT tuple_json FROM bot_composed_sms_dispatch_authorities WHERE authority_id=?').get(g.authority_id) as any).tuple_json));
 let readback:any;const scope={async prepare(_r:any,_a:any,base:any){return (fresh:any)=>{if(base.contextRevision!==fresh.contextRevision)throw Error('Scope drift');return {...fresh,schemaVersion:'compose-sms-current-context/v2' as const,blockingIds:[],holds:[],obligations:[]};};}};
 const v=composedSmsVerifier(db,{registration:()=>r,nativeCurrent:s.serviceCurrent,now:()=>clock,scope,readback:async()=>readback});
 const ctx=await v.currentContextV2(r.registrationId,g.authority_id,1,a.nativeActionId);
 const p={schemaVersion:CORRECTION_DISPATCH,nativeActionId:a.nativeActionId,authorityId:g.authority_id,authorityRevision:1,nativeClaimId:c.native_claim_id,sourcePrepareId:'60000000-0000-4000-8000-000000000001',bindingHash:correctionBindingHash(r,a),requestKey:'60000000-0000-4000-8000-000000000002',contextRevision:ctx.contextRevision,scopeEvidenceRevision:ctx.scopeEvidenceRevision,guardManifestHash:r.guardContractHash};
 readback={schemaVersion:CORRECTION_DISPATCH,nativeActionId:a.nativeActionId,prepareId:p.sourcePrepareId,bindingHash:p.bindingHash,nativeClaimId:p.nativeClaimId,associationId:null,attemptId:null,state:'REDEEMING',authorityHash:a.authorityHash,wirePayloadHash:a.wirePayloadHash,idempotencyKey:a.idempotencyKey,providerReceipt:null,observedAt:new Date(clock).toISOString(),prepareExpiresAt:new Date(clock+30000).toISOString(),redeemRequestKey:p.requestKey,execute:false,contextRevision:p.contextRevision,scopeEvidenceRevision:p.scopeEvidenceRevision,guardManifestHash:p.guardManifestHash};
 return {v,p,r,a,g,readback};
}
it('grants first service association once under accepted synthetic scope, then consumes exact source receipt without provider calls',async()=>{
 const {v,p,r,a,readback}=await dispatchFixture();const [one,two]=await Promise.all([v.associate(r.registrationId,p),v.associate(r.registrationId,p)]);expect([one,two].filter(x=>x.dispatchEntitlement)).toHaveLength(1);expect(one.associationId).toBe(two.associationId);expect(v.association(r.registrationId,one.associationId).dispatchEntitlement).toBe(false);
 readback.state='UNKNOWN';readback.associationId=one.associationId;expect(await v.receipt(r.registrationId,a.nativeActionId)).toEqual({execute:false,state:'UNKNOWN',receipt:null});expect((await v.associate(r.registrationId,p)).dispatchEntitlement).toBe(false);
 readback.state='SENT_ACCEPTED';readback.attemptId='60000000-0000-4000-8000-000000000003';readback.providerReceipt={provider:'twilio',providerAccountId:a.senderAccountId,providerMessageId:'synthetic-acceptance',fromPhone:a.fromPhone,toPhone:a.toPhone,wirePayloadHash:a.wirePayloadHash,acceptanceStatus:'accepted',deliveryStatus:null,evidenceOrigin:'synthetic-persisted-source',checkedAt:new Date(clock).toISOString()};
 expect((await v.receipt(r.registrationId,a.nativeActionId)).state).toBe('SENT_ACCEPTED');expect((await v.receipt(r.registrationId,a.nativeActionId)).execute).toBe(false);readback.providerReceipt.providerMessageId='conflict';await expect(v.receipt(r.registrationId,a.nativeActionId)).rejects.toThrow('Conflicting');
});
it.each(['hash','state','prepare','context','expiry','privateField','oldVersion'] as const)('denies %s source readback and never consumes association',async kind=>{const {v,p,r,readback}=await dispatchFixture();if(kind==='hash')readback.bindingHash='0'.repeat(64);if(kind==='state')readback.state='PREPARED';if(kind==='prepare')readback.prepareId=ids.other;if(kind==='context')readback.contextRevision='0'.repeat(64);if(kind==='expiry')readback.prepareExpiresAt=new Date(clock).toISOString();if(kind==='privateField')readback.correctionText='private';if(kind==='oldVersion')readback.schemaVersion='native-compose-sms/v3';await expect(v.associate(r.registrationId,p)).rejects.toThrow();expect(db.prepare('SELECT count(*) n FROM bot_composed_sms_associations').get()).toEqual({n:0});});
it.each(['native','revoked','custody'] as const)('revalidates %s after awaited service readback before association',async kind=>{const {p,r,a,readback}=await dispatchFixture();const v=composedSmsVerifier(db,{registration:()=>r,nativeCurrent:s.serviceCurrent,now:()=>clock,scope:{prepare:async()=>fresh=>({...fresh,blockingIds:[],holds:[],obligations:[],schemaVersion:'compose-sms-current-context/v2'})},readback:async()=>{if(kind==='native')db.prepare('UPDATE bot_decisions SET handling_revision=handling_revision+1 WHERE id=?').run(decision);if(kind==='revoked')s.revoke(owner,a.authorityId,'revoked','Synthetic revocation while awaiting source');if(kind==='custody')delete r.correctionAcceptance;return readback;}});await expect(v.associate(r.registrationId,p)).rejects.toThrow();expect(db.prepare('SELECT count(*) n FROM bot_composed_sms_associations').get()).toEqual({n:0});});
it('lost first response, expiry, source UNKNOWN and changed draft keys never renew entitlement',async()=>{const {v,p,r,readback}=await dispatchFixture();await v.associate(r.registrationId,p);expect((await v.associate(r.registrationId,p)).dispatchEntitlement).toBe(false);readback.state='UNKNOWN';clock+=3600001;await expect(v.associate(r.registrationId,p)).rejects.toThrow();expect(v.association.bind(v,r.registrationId,'not-found')).toThrow();expect(db.prepare('SELECT count(*) n FROM bot_composed_sms_associations').get()).toEqual({n:1});});
