import {it,expect} from 'vitest';
import {verifyComposeSender} from '../src/bots/composedSmsSender.js';
import {verifyComposeClosure} from '../src/bots/composedSmsClosure.js';
import {composeHash} from '../src/bots/composedSmsContract.js';
import type {ComposeRegistration} from '../src/bots/composedSmsTrust.js';
const id=(n:number)=>`10000000-0000-4000-8000-${String(n).padStart(12,'0')}`,now=Date.parse('2026-09-29T12:00:00Z'),time=(n:number)=>new Date(now+n).toISOString();
const r={registrationId:id(1),businessId:id(2),sourceAccountId:'fixture',sourceOrigin:'https://orderops-dev-web-production.up.railway.app',runtime:{projectId:id(3),environmentId:id(4),serviceId:id(5)},sourceRegistrationHash:'a'.repeat(64),senderReceiptIssuerId:id(6),expiresAt:time(60000),guardManifest:{implementationRevision:'f'.repeat(64)}} as ComposeRegistration;
function sender(){const account='AC'+'a'.repeat(32),phone='+12025550100',receipt={schemaVersion:'compose-sms-sender/v1',receiptId:id(7),revision:1,issuerId:r.senderReceiptIssuerId,authorityEvidence:'synthetic issuer evidence',provider:'twilio',providerAccountId:account,fromPhone:phone,ownershipVerified:true,smsCapable:true,active:true,sourceAccountId:r.sourceAccountId,nativeBusinessId:r.businessId,sourceOrigin:r.sourceOrigin,runtime:r.runtime,verifiedAt:time(-1000),expiresAt:time(30000),evidenceReferences:['synthetic'],revokedAt:null};const material={schemaVersion:'compose-sms-sender-observation/v1',registrationId:r.registrationId,sourceRegistrationHash:r.sourceRegistrationHash,receipt,process:{runtime:r.runtime,implementationRevision:'f'.repeat(64),processGenerationId:id(20),clientGenerationId:id(21),observedAt:time(0),configuredAccountId:account,effectiveAccountId:account,configuredFromPhone:phone,effectiveFromPhone:phone}};return {...material,observedAt:time(0),expiresAt:time(5000),snapshotHash:composeHash('compose-sms-sender-observation/v1',material)};}
it('accepts fresh authenticated issuer evidence with actual process identity',()=>{expect(verifyComposeSender(sender(),r,now)).toMatchObject({receiptId:id(7),providerAccountId:'AC'+'a'.repeat(32)});});
it.each(['expired','issuer','process','revoked','ttl','forged'] as const)('denies sender %s',kind=>{const s=sender();if(kind==='expired')s.expiresAt=time(0);if(kind==='issuer')s.receipt.issuerId=id(9);if(kind==='process')s.process.effectiveAccountId='AC'+'b'.repeat(32);if(kind==='revoked')(s.receipt as any).revokedAt=time(-1);if(kind==='ttl')s.receipt.verifiedAt=time(-900001);const {observedAt,expiresAt,snapshotHash,...material}=s;s.snapshotHash=composeHash('compose-sms-sender-observation/v1',material);if(kind==='forged')s.snapshotHash='0'.repeat(64);expect(()=>verifyComposeSender(s,r,now)).toThrow();});
function closure(){const identity={principalId:'own',fullOrderOpsAccess:true,accountId:r.sourceAccountId,nativeBusinessId:r.businessId,sourceOrigin:r.sourceOrigin,runtime:r.runtime},seeds:[string,string,string]=[id(10),id(11),id(12)];const snapshot={schemaVersion:'compose-sms-scope/v1',identity,sourceRegistrationHash:r.sourceRegistrationHash,seeds,nodes:seeds.map(value=>({id:'case:'+value,kind:'case',value,provenance:[{table:'cs_conversations',rowId:value,field:'id',storedValue:value,revision:'b'.repeat(64)}]})),edges:[] as any[],coverage:{model:'persisted-cs-case-contact-closure/v1',normalization:'ordinal-uuid-email-trim-lower-phone-nanp-evidence/v1',fixedPoint:true,complete:true,unresolved:[] as string[],omitted:[]}};const scopeEvidenceId=id(15),{principalId,...shared}=identity;return {...snapshot,scopeEvidenceId,observedAt:time(0),expiresAt:time(5000),snapshotHash:composeHash('compose-sms-scope-snapshot/v1',{...snapshot,scopeEvidenceId}),materialHash:composeHash('compose-sms-scope-material/v1',{...snapshot,identity:shared})};}
function rehash(w:ReturnType<typeof closure>){const {observedAt,expiresAt,snapshotHash,materialHash,scopeEvidenceId,...s}=w,{principalId,...identity}=s.identity;w.snapshotHash=composeHash('compose-sms-scope-snapshot/v1',{...s,scopeEvidenceId});w.materialHash=composeHash('compose-sms-scope-material/v1',{...s,identity});return w;}
it('only clears disjoint complete authenticated source components',()=>{const w=closure();expect(verifyComposeClosure(w,r,w.seeds,'own',now).disjoint).toBe(true);w.coverage.unresolved=['country context unknown'];expect(verifyComposeClosure(rehash(w),r,w.seeds,'own',now).disjoint).toBe(false);});
it('overlapping persisted edges never imply unrelatedness',()=>{const w=closure();const shared={id:'customer:'+id(19),kind:'customer',value:id(19),provenance:[{table:'cs_customers',rowId:id(19),field:'id',storedValue:id(19),revision:'d'.repeat(64)}]};w.nodes.push(shared);w.edges=[0,2].map(i=>({from:w.nodes[i]!.id,to:shared.id,kind:'case_customer',provenance:{...w.nodes[i]!.provenance[0],field:'customer_id',storedValue:id(19)}}));expect(verifyComposeClosure(rehash(w),r,w.seeds,'own',now).disjoint).toBe(false);});
it.each(['principal','seed','revision','expired'] as const)('rejects changed closure %s',kind=>{const w=closure();if(kind==='principal')w.identity.principalId='borrowed';if(kind==='seed')w.seeds[2]=id(13);if(kind==='revision')w.nodes[0]!.provenance[0]!.revision='c'.repeat(64);if(kind==='expired')w.expiresAt=time(0);expect(()=>verifyComposeClosure(w,r,[id(10),id(11),id(12)],'own',now)).toThrow();});

it('rejects a stale actual dispatcher generation even with a valid source envelope hash',()=>{const s=sender();s.process.observedAt=time(-5001);const {observedAt,expiresAt,snapshotHash,...material}=s;s.snapshotHash=composeHash('compose-sms-sender-observation/v1',material);expect(()=>verifyComposeSender(s,r,now)).toThrow('generation');});
