import Database from 'better-sqlite3';
import {beforeEach,afterEach,it,expect,vi} from 'vitest';
import {fileURLToPath} from 'node:url';
import {migrate} from '../src/db/migrate.js';
import {composedSmsReader,correspondenceRegistrySchema} from '../src/bots/composedSmsReader.js';
import {canonicalSha256} from '../src/bots/canonical.js';
import type {AppContext} from '../src/context.js';
import type {Actor} from '../src/bots/service.js';
const ids=Array.from({length:8},(_,i)=>`10000000-0000-4000-8000-${String(i+1).padStart(12,'0')}`);
let db:Database.Database,a:Actor,clock:number,registry:ReturnType<typeof correspondenceRegistrySchema.parse>,wire:any,reader:ReturnType<typeof composedSmsReader>,secret:ReturnType<typeof vi.fn>,calls:string[],mode:string;
const input=()=>({source_id:'source',draft_id:'draft',expected_draft_version:1,executor_conversation_id:ids[1]!,canonical_case:ids[3]!,contact_case:ids[4]!});
beforeEach(()=>{db=new Database(':memory:');migrate(db,fileURLToPath(new URL('../src/db/migrations',import.meta.url)));db.prepare("INSERT INTO users(id,email,display_name,role) VALUES(1,'fixture@test','Fixture','owner')").run();db.prepare("INSERT INTO business_teams(id,name,owner_id) VALUES(?,'Fixture',1)").run(ids[2]);for(const id of ids.slice(0,2)){db.prepare("INSERT INTO conversations(id,assistant_id,user_id,title,provider,native_session_id,visibility,business_team_id) VALUES(?,1,1,'fixture','codex',?,'team',?)").run(id,id,ids[2]);db.prepare("INSERT INTO bot_registrations(conversation_id,name,registered_by,active) VALUES(?,'fixture',1,1)").run(id);}db.prepare("INSERT INTO bot_message_drafts(id,conversation_id,request_key,payload_json) VALUES('draft',?,'fixture',?)").run(ids[1],JSON.stringify({channel:'sms',account:'fixture-sms'}));a={user:db.prepare('SELECT * FROM users WHERE id=1').get() as Actor['user'],conversationId:ids[0]};clock=Date.parse('2026-09-28T22:00:00Z');mode='';calls=[];
 registry=correspondenceRegistrySchema.parse({schema_version:'compose-correspondence-registry/v1',registrations:[{id:'fixture',active:true,business_id:ids[2],business_owner_user_id:1,account_id:'fixture',source_origin:'https://orderops-dev-web-production.up.railway.app',runtime:{projectId:ids[5],environmentId:ids[6],serviceId:ids[7]},payload_accounts:['fixture-sms'],expires_at:'2026-09-29T00:00:00Z',provenance:{custodian_id:ids[0],receipt:'fixture-only',registered_at:'2026-09-28T00:00:00Z',authority:'compose-send-correspondence-custody'},callers:ids.slice(0,2).map((id,i)=>({conversation_id:id,user_id:1,principal_id:'fixture'+i,credential:{project:'fixture',config:'test',name:'FIXTURE_'+i}}))}]});
 const r=registry.registrations[0]!;
 wire={schemaVersion:'approved-case-correspondence/v1',identity:{principalId:'fixture0',fullOrderOpsAccess:true,accountId:r.account_id,nativeBusinessId:r.business_id,sourceOrigin:r.source_origin,runtime:r.runtime},cases:[ids[3],ids[4]].map((id,i)=>({id,ticketNumber:'T'+i,customerId:ids[5+i],relatedOrderId:null,status:'open',updatedAt:'2026-09-28T21:00:00.123456Z',customer:{id:ids[5+i],name:null,email:null,phone:i?'+12025550111':null,updatedAt:null}})),messages:[],complete:true,counts:{cases:2,messages:0,messagesByCase:[{conversationId:ids[3],count:0},{conversationId:ids[4],count:0}]},coverage:{messageSet:'all_rows_for_exact_cases',body:'verbatim',omitted:['bodyHtml','transcription','attachments','recordingUrl','actorContext'],attachmentContent:'not_included',mediaContent:'not_included',relationClassification:'not_performed'},smsSender:{accountId:null,fromPhone:null,active:null,provenance:null,revision:null,missingProof:'SMS_SENDER_OWNERSHIP_UNVERIFIED'},observedAt:new Date(clock).toISOString(),expiresAt:new Date(clock+15000).toISOString()};rehash();
 secret=vi.fn(async()=> 'synthetic-test-only');reader=composedSmsReader({db,config:{}} as AppContext,{registry:()=>registry,now:()=>clock,secret,get:async url=>{calls.push(url);if(url.endsWith('/capabilities'))return {ok:true,access:{...wire.identity,principalId:mode==='principal'?'foreign':wire.identity.principalId}};return structuredClone(wire);}});
});
afterEach(()=>db.close());
function rehash(){const {observedAt,expiresAt,snapshotHash,...material}=wire;wire.snapshotHash=canonicalSha256(material);}
it('reads only capability-correspondence-capability and preserves nulls, distinct customers, microseconds and unknown sender',async()=>{const e=await reader(a,input(),ids[0]!);expect(calls.map(c=>c.replace(registry.registrations[0]!.source_origin,''))).toEqual(['/api/cs/approved-case/capabilities',`/api/cs/approved-case/correspondence/${ids[3]}/${ids[4]}`,'/api/cs/approved-case/capabilities']);expect(e.projection.cases[0]!.relatedOrderId).toBeNull();expect(e.projection.cases[0]!.customerId).not.toBe(e.projection.cases[1]!.customerId);expect(e.sender_verified).toBe(false);expect(e.dispatch.supported).toBe(false);});
it.each(['hash','count','principal','case','customer','expiry','sender'])('rejects %s evidence',async kind=>{if(kind==='hash')wire.snapshotHash='0'.repeat(64);if(kind==='count'){wire.counts.messages=1;rehash();}if(kind==='principal')mode='principal';if(kind==='case'){wire.cases.reverse();rehash();}if(kind==='customer'){wire.cases[0].customer.id=ids[7];rehash();}if(kind==='expiry')clock+=15000;if(kind==='sender'){wire.smsSender.active=true;rehash();}await expect(reader(a,input(),ids[0]!)).rejects.toThrow();});
it('requires separate endpoint custody and denies revoked registration before secret use',async()=>{registry.registrations[0]!.active=false;await expect(reader(a,input(),ids[0]!)).rejects.toThrow();expect(secret).not.toHaveBeenCalled();expect(correspondenceRegistrySchema.safeParse({...registry,schema_version:'approved-case-registry/v1'}).success).toBe(false);});
it('rechecks registration and observation at use time',async()=>{const e=await reader(a,input(),ids[0]!);clock+=5001;expect(e.assertFresh).toThrow('expired');clock-=5001;registry.registrations[0]!.callers[0]!.principal_id='changed';expect(e.assertFresh).toThrow('custody');});
it('uses own identity for executor but keeps identical material digest',async()=>{const owner=await reader(a,input(),ids[0]!);wire.identity.principalId='fixture1';rehash();const executor=await reader({...a,conversationId:ids[1]},input(),ids[0]!);expect(executor.snapshot_hash).toBe(owner.snapshot_hash);expect(executor.principal_id).not.toBe(owner.principal_id);});

it('denies out-of-custody draft accounts before credential retrieval',async()=>{registry.registrations[0]!.payload_accounts=['foreign'];await expect(reader(a,input(),ids[0]!)).rejects.toThrow('custody');expect(secret).not.toHaveBeenCalled();});
