import fs from 'node:fs';
import {it,expect} from 'vitest';
import {canonicalJson,canonicalSha256} from '../src/bots/canonical.js';
import {composeHash,wireSchema} from '../src/bots/composedSmsContract.js';
import {CORRECTION_DISPATCH,verifyCorrectionDispatch,verifyLineage,lineageHash,correctionScopeHash,correctionBindingHash,correctionEnvelopeSchema,correctionAssociationSchema,correctionReadbackSchema,correctionPrepareSchema,correctionPrepareResultSchema,correctionDispatchInputSchema,correctionAssociationResultSchema} from '../src/bots/composedSmsCorrectionContract.js';
const g=JSON.parse(fs.readFileSync(new URL('../../docs/reports/composed-sms/correction-integration-proposal-v1/golden.json',import.meta.url),'utf8'));
it('parses the accepted golden bytes and verifies all seven fixed digest domains without regenerating values',()=>{
 const a=verifyCorrectionDispatch(g.authority),l=verifyLineage(g.lineage),wire=wireSchema.parse(Object.fromEntries(Object.keys(wireSchema.shape).map(k=>[k,(a as any)[k]]))),{authorityHash,...tuple}=a;
 expect(canonicalSha256(g.payload)).toBe(a.payloadHash);expect(composeHash('native-compose-sms/wire/v1',wire)).toBe(a.wirePayloadHash);expect(correctionScopeHash(a)).toBe(a.scopeHash);expect(lineageHash(l)).toBe(a.lineageHash);expect(canonicalSha256({business_id:l.businessId,decision_id:l.decisionId,channel:'sms'})).toBe(a.originalActionDigest);expect(composeHash('native-compose-sms/correction-dispatch-authority/v1',tuple)).toBe(authorityHash);expect(correctionBindingHash({...g.registration,revision:g.registration.registrationRevision},a)).toBe(g.bindingHash);expect(canonicalJson(tuple)).toBe(g.canonicalAuthorityWithoutHash);
 expect(correctionEnvelopeSchema.parse({schemaVersion:CORRECTION_DISPATCH,...g.registration,authority:a,lineage:l,observedAt:a.derivedAt,expiresAt:'2026-09-29T00:00:15.000Z',execute:false}).authority).toEqual(a);
});
it.each(['payloadHash','correctionSourceHash','contextHash','reviewHash','originalActionDigest','lineageHash','authorityExpiresAt','wireBody','executorConversationId'])('rejects missing or tampered %s without reinterpreting v1',field=>{const value={...g.authority};delete value[field];expect(()=>verifyCorrectionDispatch(value)).toThrow();expect(()=>verifyCorrectionDispatch({...g.authority,[field]:'0'.repeat(64)})).toThrow();});
it('strictly parses all locator, association and readback DTOs and refuses unknown private fields/version',()=>{
 const a=verifyCorrectionDispatch(g.authority),ids={nativeActionId:a.nativeActionId,authorityId:a.authorityId,authorityRevision:1},extra={contextRevision:'a'.repeat(64),scopeEvidenceRevision:'b'.repeat(64),guardManifestHash:'c'.repeat(64)},claim=g.lineage.businessId;
 const prepare={schemaVersion:CORRECTION_DISPATCH,...ids};expect(correctionPrepareSchema.parse(prepare)).toEqual(prepare);expect(()=>correctionPrepareSchema.parse({...prepare,body:a.wireBody})).toThrow();expect(correctionDispatchInputSchema.parse({schemaVersion:CORRECTION_DISPATCH,nativeClaimId:claim})).toBeTruthy();
 const assoc={...prepare,nativeClaimId:claim,sourcePrepareId:claim,bindingHash:g.bindingHash,requestKey:claim,...extra};expect(correctionAssociationSchema.parse(assoc)).toEqual(assoc);expect(()=>correctionAssociationSchema.parse({...assoc,schemaVersion:'native-compose-sms/v3'})).toThrow();
 expect(correctionPrepareResultSchema.parse({schemaVersion:CORRECTION_DISPATCH,prepareId:claim,nativeActionId:a.nativeActionId,bindingHash:g.bindingHash,state:'PREPARED',observedAt:a.derivedAt,prepareExpiresAt:a.authorityExpiresAt,execute:false})).toBeTruthy();
 expect(correctionAssociationResultSchema.parse({schemaVersion:CORRECTION_DISPATCH,associationId:claim,nativeActionId:a.nativeActionId,nativeClaimId:claim,sourcePrepareId:claim,bindingHash:g.bindingHash,state:'ASSOCIATED',dispatchEntitlement:true,execute:false,issuedAt:a.derivedAt,expiresAt:a.authorityExpiresAt})).toBeTruthy();
 const readback={schemaVersion:CORRECTION_DISPATCH,nativeActionId:a.nativeActionId,prepareId:claim,bindingHash:g.bindingHash,nativeClaimId:claim,associationId:null,attemptId:null,state:'REDEEMING',authorityHash:a.authorityHash,wirePayloadHash:a.wirePayloadHash,idempotencyKey:a.idempotencyKey,providerReceipt:null,observedAt:a.derivedAt,prepareExpiresAt:a.authorityExpiresAt,redeemRequestKey:claim,execute:false,...extra};expect(correctionReadbackSchema.parse(readback)).toEqual(readback);expect(()=>correctionReadbackSchema.parse({...readback,redeemRequestKey:null})).toThrow();expect(()=>correctionReadbackSchema.parse({...readback,humanText:'private'})).toThrow();
});
