/**
 * Normalized event model (spec §6). All providers map into this; the UI
 * consumes only this. The full union is declared to keep the seam for
 * approvals/questions/documents, though the prototype only emits a subset.
 */

export type Channel = 'web' | 'email' | 'automation';
export type SubagentStatus = 'queued' | 'running' | 'completed' | 'stopped' | 'failed';
export type TurnOutcome = 'completed' | 'interrupted_by_user' | 'timed_out' | 'failed';

/** Authenticated origin for a prompt that was not authored by the human.
 * Omitted means the ordinary user authored the message. */
export interface MessageOrigin {
  kind: 'agent' | 'wakeup' | 'build_queue' | 'result_reply';
  /** Durable internal build activation; never inferred from prompt text. */
  buildDispatchId?: string;
  from: string;
  to: string;
  /** Viewer-safe marker for a message sent from another chat on this instance.
   * Unlike sourceConversationId, this does not grant or imply source access. */
  local?: true;
  /** Internal provenance used to resolve a viewer-authorized source link.
   * Presentation boundaries must strip this raw id before sending events. */
  sourceConversationId?: string;
  /** Send-time title paired with the internal source id. It follows the same
   * privacy rule and is stripped unless the viewer can access that source. */
  sourceConversationTitle?: string;
  /** Viewer-authorized source metadata. Never persist this presentation view. */
  sourceChat?: {
    id: string;
    title: string;
  };
}

export type AgentMessageDisposition = 'running' | 'steered' | 'delivered' | 'queued' | 'duplicate';

/** Structured sender-side receipt for mcp__agents__send_message. Raw target ids
 * stay server-side; presentation replaces them with viewer-authorized links. */
export interface AgentMessageToolDetails {
  kind: 'agent-message';
  text: string;
  targetConversationId?: string;
  remoteInstance?: string;
  disposition?: AgentMessageDisposition;
  messageId?: number;
  targetChat?: {
    id: string;
    title: string;
    agentName: string;
  };
}

/** Safe, provider-neutral aggregates for delegated work. Provider-native ids,
 * prompts, commands, logs, reasoning, results, and file paths never belong
 * here. Every field is optional because providers expose different detail. */
export interface SubagentProgress {
  startedAt?: string;
  durationMs?: number;
  currentAction?: string;
  actionCount?: number;
  filesChanged?: number;
  linesAdded?: number;
  linesRemoved?: number;
  resultLabel?: string;
}

export interface QuestionOption {
  label: string;
  value: string;
  description?: string;
}

/** Where a 'secret' prompt's value is written. The value itself never travels
 * through a prompt, an event, or the questions table. */
export interface QuestionSecretTarget {
  name: string;
  project: string | null;
  config: string | null;
  /** Best-effort: the name already has a value in that config. */
  exists?: boolean;
}

/** Public, provider-neutral question ids are generated by Veneer (q1, q2...). */
export interface QuestionPrompt {
  id: string;
  header?: string;
  question: string;
  options: QuestionOption[];
  multi: boolean;
  allowOther: boolean;
  /** Omitted means 'choice' (every pre-secret prompt). 'reveal' shows an
   * existing Doppler secret to the user only; the agent never sees the value. */
  kind?: 'choice' | 'secret' | 'reveal';
  secret?: QuestionSecretTarget;
}

export type QuestionAnswers = Record<string, string[]>;

/** Human identity for an MCP tool backed by one installed connector. The raw
 * toolName remains authoritative for execution; this is durable presentation
 * metadata so transcripts never need to expose the routing name. */
export interface ConnectorToolSource {
  kind: 'connector';
  slug: string;
  name: string;
  mention: string;
  action: string;
  installId?: number;
  label?: string;
  sharing?: 'personal' | 'shared';
}

/** Allowlisted, connector-specific fields safe to send to the chat UI. Raw
 * connector payloads stay in the provider transcript and never cross this
 * normalized event seam. Add new variants as connector renderers are built. */
interface GmailResultConnectorDetails {
  successful?: boolean;
  error?: string;
  gmailUrl?: string;
}

export interface GmailMessageSummary {
  /** Opaque, non-reversible correlation key. Never render this value. */
  messageRef?: string;
  threadRef?: string;
  subject?: string;
  sender?: string;
  receivedAt?: string;
  preview?: string;
}

export interface GmailForwardConnectorDetails extends GmailResultConnectorDetails {
  kind: 'gmail-forward';
  messageRef?: string;
  recipients?: string[];
  note?: string;
  sourceSubject?: string;
  sourceSender?: string;
}

export interface GmailSendConnectorDetails extends GmailResultConnectorDetails {
  kind: 'gmail-send';
  recipients?: string[];
  subject?: string;
  body?: string;
}

export interface GmailFetchListConnectorDetails extends GmailResultConnectorDetails {
  kind: 'gmail-fetch-list';
  searchSummary?: string;
  resultCount?: number;
  resultEstimate?: number;
  hasMore?: boolean;
  messages?: GmailMessageSummary[];
}

export interface GmailFetchThreadConnectorDetails extends GmailResultConnectorDetails {
  kind: 'gmail-fetch-thread';
  threadRef?: string;
  subject?: string;
  latestSender?: string;
  latestAt?: string;
  messageCount?: number;
  messages?: GmailMessageSummary[];
}

export interface GmailFetchMessageConnectorDetails extends GmailResultConnectorDetails {
  kind: 'gmail-fetch-message';
  messageRef?: string;
  threadRef?: string;
  subject?: string;
  sender?: string;
  receivedAt?: string;
  preview?: string;
}

export interface GmailReplyConnectorDetails extends GmailResultConnectorDetails {
  kind: 'gmail-reply';
  threadRef?: string;
  recipients?: string[];
  body?: string;
  subject?: string;
}

export interface GoogleDriveFileSummary {
  name?: string;
  fileType?: string;
  modifiedAt?: string;
  driveUrl?: string;
}

export interface GoogleDriveFindFileConnectorDetails {
  kind: 'google-drive-find-file';
  successful?: boolean;
  searchSummary?: string;
  resultCount?: number;
  hasMore?: boolean;
  files?: GoogleDriveFileSummary[];
}

export interface GoogleSheetsFileSummary {
  name?: string;
  url?: string;
  modifiedAt?: string;
}

export type GoogleSheetsOperation =
  | 'info' | 'read' | 'write' | 'append' | 'clear' | 'search' | 'create' | 'lookup' | 'other';

export interface GoogleSheetsConnectorDetails {
  kind: 'google-sheets';
  operation: GoogleSheetsOperation;
  successful?: boolean;
  actionLabel?: string;
  spreadsheetTitle?: string;
  spreadsheetUrl?: string;
  sheetNames?: string[];
  hasMoreSheets?: boolean;
  range?: string;
  rowCount?: number;
  columnCount?: number;
  updatedCells?: number;
  updatedRows?: number;
  searchSummary?: string;
  resultCount?: number;
  hasMore?: boolean;
  files?: GoogleSheetsFileSummary[];
  error?: string;
}

export type ConnectorToolDetails =
  | GmailForwardConnectorDetails
  | GmailSendConnectorDetails
  | GmailFetchListConnectorDetails
  | GmailFetchThreadConnectorDetails
  | GmailFetchMessageConnectorDetails
  | GmailReplyConnectorDetails
  | GoogleDriveFindFileConnectorDetails
  | GoogleSheetsConnectorDetails;

export interface TokenUsage {
  /** Latest provider-call input, used only for context-window occupancy. */
  inputTokens: number;
  /** Provider output retained for existing consumers. */
  outputTokens: number;
  /** Whole-turn usage. Missing on older events and providers without a reliable total. */
  totalInputTokens?: number;
  totalOutputTokens?: number;
  totalTokens?: number;
  /** Whole-turn cache reads, a subset of totalInputTokens. Provider-dependent. */
  cachedInputTokens?: number;
  /** Whole-turn cache writes, a subset of totalInputTokens. Claude only. */
  cacheWriteInputTokens?: number;
  contextPct?: number;
}

export type ConversationEvent =
  | {
      type: 'turn_started';
      turnId: string;
      role: 'user';
      text: string;
      at: string;
      via: Channel;
      origin?: MessageOrigin;
      /** Durable queued_messages id used by agent handoff deep links. */
      messageId?: number;
    }
  | { type: 'text_delta'; turnId: string; text: string } // live only, not persisted
  | {
      type: 'text_final';
      turnId: string;
      markdown: string;
      at: string;
      /** Whole-turn usage attached to the turn's final response on transcript reload. */
      usage?: TokenUsage;
    }
  | { type: 'thinking'; turnId: string; summary?: string }
  | {
      type: 'tool_started';
      turnId: string;
      toolId: string;
      toolName: string;
      displayName: string;
      inputPreview: string;
      source?: ConnectorToolSource;
      connectorDetails?: ConnectorToolDetails;
      agentMessageDetails?: AgentMessageToolDetails;
    }
  // images: media-store ids (runtime/media.ts) for image blocks in the tool
  // result — screenshots, Read on an image, etc. Served at GET /api/media/:id.
  | {
      type: 'tool_finished';
      turnId: string;
      toolId: string;
      ok: boolean;
      resultPreview?: string;
      images?: string[];
      connectorDetails?: ConnectorToolDetails;
      agentMessageDetails?: AgentMessageToolDetails;
    }
  | ({
      type: 'subagent_started';
      turnId: string;
      agentKey: string;
      label: string;
      model?: string;
      role?: string;
      effort?: string;
      status: SubagentStatus;
    } & SubagentProgress)
  | ({
      type: 'subagent_updated';
      turnId: string;
      agentKey: string;
      status: SubagentStatus;
      label?: string;
      model?: string;
      role?: string;
      effort?: string;
    } & SubagentProgress)
  // approvalId/displayName/inputPreview extend spec §6 so the UI can render and
  // resolve the card without a lookup; approvalId is filled in by the manager
  // (the adapter doesn't know DB ids). outcome 'expired' = 10-min auto-deny.
  | {
      type: 'approval_requested';
      requestId: string;
      approvalId?: number;
      toolName: string;
      displayName: string;
      input: unknown;
      inputPreview: string;
      policyReason: string;
    }
  | { type: 'approval_resolved'; requestId: string; outcome: 'approved' | 'denied' | 'expired'; byUserId?: number }
  | {
      type: 'question_asked';
      requestId: string;
      turnId: string;
      questions: QuestionPrompt[];
      responseMode: 'poll' | 'provider';
      blocking?: boolean;
      autoResolutionMs?: number | null;
      /** Legacy live events from pre-0081 runners. */
      question?: string;
      options?: QuestionOption[];
      multi?: boolean;
    }
  // expired = the wait timed out or the turn ended before the user answered.
  // dismissed = the user chatted instead of choosing an option.
  | {
      type: 'question_answered';
      requestId: string;
      answers: QuestionAnswers;
      expired?: boolean;
      dismissed?: boolean;
      /** Legacy live events from pre-0081 runners. */
      answer?: string;
    }
  // Per-prompt Supermemory recall captured when the remembered-context block is
  // built. Emitted live right after turn_started; merged back into reloaded
  // transcripts from the turn_recall table (see routes/api.ts).
  | {
      type: 'memory_recall';
      turnId: string;
      memories: Array<{
        id: string;
        content: string;
        similarity: number | null;
        scope: 'profile' | 'global' | 'project';
        source: 'profile' | 'search';
        relevance: 'profile' | 'direct' | 'semantic';
      }>;
    }
  | { type: 'files_produced'; documentIds: number[] }
  | {
      type: 'turn_done';
      turnId: string;
      /** Why this provider turn ended. Older emitters omit it and are treated as completed. */
      outcome?: TurnOutcome;
      usage?: TokenUsage;
    }
  /** Live maintenance signal; refreshes the gauge and may add a normalized notice. */
  | { type: 'context_compacted'; contextTokens: number | null; notice?: string }
  // A neutral, non-failure notice (e.g. "you stopped this turn"). Rendered muted;
  // error rows are red, while turn_done remains authoritative for final status.
  | { type: 'notice'; message: string; at?: string }
  | { type: 'error'; message: string; fatal: boolean; turnId?: string };

export type ConversationStatus = 'working' | 'needs_you' | 'idle' | 'failed';
export type ConversationActivity = 'compacting' | null;

export const CONTEXT_COMPACTED_NOTICE = 'Context compacted.';
/** Shown when the runner was killed mid-turn and Claude resumed itself on restart. */
export const VENEER_RESTARTED_NOTICE =
  'Veneer restarted while this turn was running; the agent picked up where it left off.';
/**
 * Same session-file bookkeeping as a runner restart, but a recorded turn_stops row
 * proves the user pressed Stop. Spliced over the restart notice on snapshot.
 */
export const USER_STOPPED_NOTICE = 'You stopped this turn.';

/** Durable messages waiting behind the active turn, in execution order. */
export interface QueuedMessageSnapshot {
  id: number;
  text: string;
  createdAt: string;
  /** Present when another agent, the scheduler, or the build queue queued this message. Carries
   * internal provenance inside the runner; presentation boundaries strip it. */
  origin?: MessageOrigin;
  /** The live agent process already holds this text; the row is only a fallback. */
  delivered?: true;
}

/** An interrupted turn that exhausted automatic restart recovery. */
export interface FailedTurnSnapshot {
  prompt: string;
  attempts: number;
  error: string;
}

/** Server-authoritative non-transcript state sent on subscribe and every mutation. */
export interface ConversationQueueSnapshot {
  /** Monotonic creation order. A client must not apply an older snapshot. */
  revision: number;
  messages: QueuedMessageSnapshot[];
  failedTurn: FailedTurnSnapshot | null;
}

/** Friendly one-liners for the prototype's built-in tools. */
const TOOL_DISPLAY_NAMES: Record<string, string> = {
  WebSearch: 'Searching the web',
  WebFetch: 'Reading a web page',
  Read: 'Reading a file',
  Write: 'Writing a file',
  Edit: 'Editing a file',
  Task: 'Working on a subtask',
  TodoWrite: 'Organizing the plan',
};

export function displayNameForTool(toolName: string): string {
  const known = TOOL_DISPLAY_NAMES[toolName];
  if (known) return known;
  // The built-in ask_user tool renders its own interactive question card; give
  // its accompanying tool row a friendlier label than "Using agents".
  if (toolName === 'mcp__agents__ask_user') return 'Asking you a question';
  if (toolName === 'mcp__agents__request_secret') return 'Asking you for a secret';
  if (toolName === 'mcp__agents__reveal_secret') return 'Showing you a secret';
  if (toolName.startsWith('mcp__')) {
    const parts = toolName.split('__');
    return `Using ${parts[1] ?? 'a connection'}`;
  }
  return `Using ${toolName}`;
}

export function previewOf(value: unknown, max = 200): string {
  let text: string;
  if (typeof value === 'string') text = value;
  else {
    try {
      text = JSON.stringify(value) ?? '';
    } catch {
      text = String(value);
    }
  }
  text = text.replace(/\s+/g, ' ').trim();
  return text.length > max ? `${text.slice(0, max)}…` : text;
}
